# Lectura de paquetes y data

In [1]:
import warnings
import os
import time
import sys

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from statsmodels.tsa.seasonal import STL

from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import ElasticNet
from sklearn.neighbors import KNeighborsRegressor

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.metrics import mean_absolute_error, mean_squared_error

import optuna

optuna.logging.set_verbosity(optuna.logging.WARNING)  # Reduce verbosity de Optuna


# Agrega todo el directorio padre al path
sys.path.append(os.path.abspath(".."))
from src.utils_ml import ml_training_utils as ml_utils
from src.utils_ml import ml_feature_engineering as fe_utils
from src.utils_ml import ml_plotting as plot_utils

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
warnings.filterwarnings("ignore")

/opt/homebrew/Caskroom/miniconda/base/envs/maestria/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Utilizamos paths relativos para la lectura de la data

In [2]:
filename = "ml_pipeline_p_sku.ipynb"  # nombre del archivo actual
print(f"Current absolute path: {os.getcwd()}\n")

# Especificamos la ruta del directorio actual y los directorios de datos y salida
ACTUAL_DIR = os.path.dirname(os.path.abspath(filename))
BASE_DIR = os.path.dirname(ACTUAL_DIR)
DATA_DIR = os.path.join(BASE_DIR, "data")
OUTPUT_DIR = os.path.join(DATA_DIR, "output")

print(f"BASE_DIR: {BASE_DIR}")
print(f"DATA_DIR: {DATA_DIR}")
print(f"OUTPUT_DIR: {OUTPUT_DIR}")

Current absolute path: /Users/jhonattan.reales/Documents/Personal_jhonattan/Icesi/Innova_tec1/innv_tec_1_icesi/notebooks

BASE_DIR: /Users/jhonattan.reales/Documents/Personal_jhonattan/Icesi/Innova_tec1/innv_tec_1_icesi
DATA_DIR: /Users/jhonattan.reales/Documents/Personal_jhonattan/Icesi/Innova_tec1/innv_tec_1_icesi/data
OUTPUT_DIR: /Users/jhonattan.reales/Documents/Personal_jhonattan/Icesi/Innova_tec1/innv_tec_1_icesi/data/output

In [3]:
# Cargar el archivo de Excel
file_path = os.path.join(DATA_DIR, "data_demanda.xlsx")
df_base = pd.read_excel(file_path, sheet_name="data")
df_base = df_base.drop("Cliente", axis=1)

df_base.shape

(6834, 11)

In [4]:
df_base.head(5)

,Fe.prefer.entrega,Day_of_the_Week,Pedidos,Sell_In,Sell_in_on_time,CEDIS,SKU,Mes_Año,Sell_in_rezago,porcentaje_on_time,Subcategoria
0,2024-07-05,Friday,16200,16200,16200,7,SKU7,72024,0,1.0,BEBIDAS DE YOGUR
1,2024-07-05,Friday,19800,19800,19800,6,SKU5,72024,0,1.0,BEBIDAS DE YOGUR
2,2024-07-05,Friday,4950,4950,4950,4,SKU6,72024,0,1.0,BEBIDAS DE YOGUR
3,2024-07-05,Friday,8100,8100,8100,6,SKU4,72024,0,1.0,BEBIDAS DE YOGUR
4,2024-07-05,Friday,18600,18600,18600,7,SKU3,72024,0,1.0,BEBIDAS DE YOGUR

In [5]:
# Filtrar los datos relevantes para este analisis

df = (
    df_base[["Fe.prefer.entrega", "SKU", "Pedidos"]]
    .copy()
    .rename(
        columns={
            "Fe.prefer.entrega": "Fecha",
        }
    )
)
df["Pedidos"] = pd.to_numeric(df["Pedidos"], errors="coerce")

In [6]:
df

          Fecha    SKU  Pedidos
0    2024-07-05   SKU7    16200
1    2024-07-05   SKU5    19800
2    2024-07-05   SKU6     4950
3    2024-07-05   SKU4     8100
4    2024-07-05   SKU3    18600
...         ...    ...      ...
6829 2025-04-10  SKU14     1560
6830 2025-04-10  SKU16     3900
6831 2025-04-10   SKU8     4200
6832 2025-04-10  SKU22     2160
6833 2025-04-10  SKU15      840

[6834 rows x 3 columns]

# Preparación de la data

In [7]:
### Primero, nos aseguramos de que se cuente un dato por SKU por dia
# -------

# rango completo de fechas desde la más antigua hasta la más reciente
fecha_min = df["Fecha"].min()
fecha_max = df["Fecha"].max()
rango_fechas = pd.date_range(start=fecha_min, end=fecha_max, freq="D")

# Obtenemos todos los SKUs únicos
skus = df["SKU"].unique()

# DataFrame con todas las combinaciones de SKU y fecha
combinaciones_completas = pd.MultiIndex.from_product(
    [rango_fechas, skus], names=["Fecha", "SKU"]
).to_frame(index=False)

# Unir con el dataframe original para rellenar con ceros donde falten datos
df_completo = combinaciones_completas.merge(df, on=["Fecha", "SKU"], how="left")

# Rellenar valores faltantes de pedidos con 0
df_completo["Pedidos"] = df_completo["Pedidos"].fillna(0).astype(int)

# Ordenar por SKU y Fecha (opcional)
df_completo = df_completo.sort_values(["SKU", "Fecha"]).reset_index(drop=True)

df = df_completo.copy()

In [8]:
# Modificar nombre de columnas
df.columns = df.columns.str.replace(".", "_", regex=False).str.lower()

In [9]:
df.shape

(7280, 3)

# EDA

## general

In [10]:
df.isna().sum()

fecha      0
sku        0
pedidos    0
dtype: int64

In [11]:
# porcentaje de ceros por sku
porcentaje_ceros = (
    df.groupby("sku")["pedidos"]
    .apply(lambda x: (x == 0).mean() * 100)
    .reset_index(name="prct_ceros")
    .round(2)
)

# promedio, mediana y desviacion estandar por sku excluyendo ceros
df_temp = df[df["pedidos"] > 0].copy()
promedio = df_temp.groupby("sku")["pedidos"].mean().reset_index(name="Promedio").round()
mediana = df_temp.groupby("sku")["pedidos"].median().reset_index(name="Mediana").round()
desviacion = (
    df_temp.groupby("sku")["pedidos"].std().reset_index(name="Desviacion").round()
)
maximo = df_temp.groupby("sku")["pedidos"].max().reset_index(name="Maximo").round()

# Porcentaje de valores outliers por SKU excluyendo ceros
porcentaje_outliers = (
    df_temp.groupby("sku")["pedidos"]
    .apply(fe_utils.calcular_outliers_porcentaje)
    .reset_index(name="prct_outliers")
    .round(2)
)

# Unir las tablas
tabla_total = pd.merge(porcentaje_ceros, porcentaje_outliers, on="sku", how="outer")
tabla_total = pd.merge(tabla_total, promedio, on="sku", how="outer")
tabla_total = pd.merge(tabla_total, mediana, on="sku", how="outer")
tabla_total = pd.merge(tabla_total, desviacion, on="sku", how="outer")
tabla_total = pd.merge(tabla_total, maximo, on="sku", how="outer")
tabla_total.sort_values(by="prct_ceros", ascending=False)

      sku  prct_ceros  prct_outliers  Promedio  Mediana  Desviacion  Maximo
6   SKU15       16.79           7.30    1004.0    840.0       647.0    3960
7   SKU16       14.29           2.08    4624.0   4688.0      1172.0    7500
0    SKU1       12.50           1.63   17878.0  15000.0     13859.0   84600
24   SKU8       11.79           5.26    1067.0    900.0       893.0    5160
4   SKU13       11.07           4.42     502.0    420.0       285.0    1500
3   SKU12       10.36           3.59     460.0    420.0       283.0    1800
8   SKU17        7.86           2.71   11496.0   9030.0      7494.0   52200
25   SKU9        7.86           8.53     799.0    600.0       641.0    6000
5   SKU14        7.86           2.71    2706.0   1920.0      2088.0   15240
10  SKU19        6.07           3.42    3103.0   2640.0      1959.0   10800
14  SKU22        5.36           1.13    2712.0   2280.0      1837.0    8400
12  SKU20        4.64           6.37    6375.0   5040.0      5239.0   36840
17  SKU25        4.64           2.25    1744.0   1560.0       983.0    5760
1   SKU10        4.29           1.49     921.0    900.0       485.0    3300
23   SKU7        4.29           0.75   10415.0  10200.0      4511.0   25200
2   SKU11        4.29           3.36     958.0    900.0       533.0    3900
9   SKU18        3.93           0.74    2161.0   2160.0      1059.0    5640
15  SKU23        2.86           6.99    3597.0   3000.0      2535.0   14640
18  SKU26        2.86           1.84    1690.0   1560.0       929.0    5760
22   SKU6        2.86           0.74    3338.0   3000.0      1571.0    9150
13  SKU21        2.86           5.88    3203.0   2400.0      2663.0   17160
21   SKU5        2.50           1.83   14412.0  15000.0      5881.0   42000
19   SKU3        2.14           1.09   14231.0  15000.0      5348.0   33000
11   SKU2        1.79           2.55    4926.0   4500.0      1948.0   10500
16  SKU24        1.79           6.18    3526.0   3000.0      2358.0   16200
20   SKU4        1.79           1.09    5446.0   5250.0      2268.0   13350

## Tendencias

In [12]:
sku = "SKU5"
print(f"Analizando el SKU: {sku}")

Analizando el SKU: SKU5

In [13]:
df_sku = df[df["sku"] == sku].copy()
df_sku = df_sku.drop("sku", axis=1)

# graficamos la serie de tiempo del SKU seleccionado usando plotly
fig = px.line(
    df_sku,
    x="fecha",
    y="pedidos",
    title=f"Serie de tiempo de Pedidos para {sku}:",
)
fig.update_layout(
    xaxis_title="Fecha",
)
fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor="LightGray")
fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor="LightGray")
fig.update_traces(line=dict(color="blue", width=2))
fig.show()

### Descomposición STL

In [14]:
# graficamos la tendencia y estacionalidad de cada SKU usando STL
plot_utils.graficar_serie_con_descomposicion(df_sku, sku=sku, periodo=7)

# Feature engineering

## Variables temporales

In [15]:
df = fe_utils.create_temporal_features(df, "fecha")
df.shape, df.columns

((7280, 10),
 Index(['fecha', 'sku', 'pedidos', 'day_of_week', 'day_of_month', 'is_weekend',
        'week_of_month', 'is_start_of_month', 'is_near_quincena',
        'is_vacation'],
       dtype='object'))

## Variables tipo lag

In [16]:
df = fe_utils.create_lag_features(
    df, "pedidos", "sku", "fecha", max_daily_lag=14, weekday_lags=3
)
df.shape, df.columns

((7280, 27),
 Index(['fecha', 'sku', 'pedidos', 'day_of_week', 'day_of_month', 'is_weekend',
        'week_of_month', 'is_start_of_month', 'is_near_quincena', 'is_vacation',
        'pedidos_lag_1', 'pedidos_lag_2', 'pedidos_lag_3', 'pedidos_lag_4',
        'pedidos_lag_5', 'pedidos_lag_6', 'pedidos_lag_7', 'pedidos_lag_8',
        'pedidos_lag_9', 'pedidos_lag_10', 'pedidos_lag_11', 'pedidos_lag_12',
        'pedidos_lag_13', 'pedidos_lag_14', 'pedidos_weekday_lag_1',
        'pedidos_weekday_lag_2', 'pedidos_weekday_lag_3'],
       dtype='object'))

## Variables tipo promedio moviles

In [17]:
df = fe_utils.create_rolling_features(df, "pedidos", "sku", "fecha")
df.shape, df.columns

((7280, 32),
 Index(['fecha', 'sku', 'pedidos', 'day_of_week', 'day_of_month', 'is_weekend',
        'week_of_month', 'is_start_of_month', 'is_near_quincena', 'is_vacation',
        'pedidos_lag_1', 'pedidos_lag_2', 'pedidos_lag_3', 'pedidos_lag_4',
        'pedidos_lag_5', 'pedidos_lag_6', 'pedidos_lag_7', 'pedidos_lag_8',
        'pedidos_lag_9', 'pedidos_lag_10', 'pedidos_lag_11', 'pedidos_lag_12',
        'pedidos_lag_13', 'pedidos_lag_14', 'pedidos_weekday_lag_1',
        'pedidos_weekday_lag_2', 'pedidos_weekday_lag_3', 'pedidos_rolling_2',
        'pedidos_rolling_7', 'pedidos_prev_week_avg', 'pedidos_dow_avg_2wks',
        'pedidos_dow_avg_3wks'],
       dtype='object'))

## Variables lags de STL

In [18]:
df = fe_utils.create_stl_features(
    df, "pedidos", "sku", "fecha", seasonal=7, stl_lags=14
)
df.shape, df.columns

((7280, 60),
 Index(['fecha', 'sku', 'pedidos', 'day_of_week', 'day_of_month', 'is_weekend',
        'week_of_month', 'is_start_of_month', 'is_near_quincena', 'is_vacation',
        'pedidos_lag_1', 'pedidos_lag_2', 'pedidos_lag_3', 'pedidos_lag_4',
        'pedidos_lag_5', 'pedidos_lag_6', 'pedidos_lag_7', 'pedidos_lag_8',
        'pedidos_lag_9', 'pedidos_lag_10', 'pedidos_lag_11', 'pedidos_lag_12',
        'pedidos_lag_13', 'pedidos_lag_14', 'pedidos_weekday_lag_1',
        'pedidos_weekday_lag_2', 'pedidos_weekday_lag_3', 'pedidos_rolling_2',
        'pedidos_rolling_7', 'pedidos_prev_week_avg', 'pedidos_dow_avg_2wks',
        'pedidos_dow_avg_3wks', 'stl_trend_lag_1', 'stl_trend_lag_2',
        'stl_trend_lag_3', 'stl_trend_lag_4', 'stl_trend_lag_5',
        'stl_trend_lag_6', 'stl_trend_lag_7', 'stl_trend_lag_8',
        'stl_trend_lag_9', 'stl_trend_lag_10', 'stl_trend_lag_11',
        'stl_trend_lag_12', 'stl_trend_lag_13', 'stl_trend_lag_14',
        'stl_seasonal_lag_1', 'stl_seasonal_lag_2', 'stl_seasonal_lag_3',
        'stl_seasonal_lag_4', 'stl_seasonal_lag_5', 'stl_seasonal_lag_6',
        'stl_seasonal_lag_7', 'stl_seasonal_lag_8', 'stl_seasonal_lag_9',
        'stl_seasonal_lag_10', 'stl_seasonal_lag_11', 'stl_seasonal_lag_12',
        'stl_seasonal_lag_13', 'stl_seasonal_lag_14'],
       dtype='object'))

## Aplanamiento de outliers en demanda

In [19]:
df = fe_utils.cap_upper_outliers(df, "pedidos", "sku")

## Ajustes finales a la data

In [20]:
# Eliminamos todas las filas con valores NaN para que no afecten el entrenamiento
df.dropna(inplace=True)
df.shape, df.columns

((6543, 60),
 Index(['fecha', 'sku', 'pedidos', 'day_of_week', 'day_of_month', 'is_weekend',
        'week_of_month', 'is_start_of_month', 'is_near_quincena', 'is_vacation',
        'pedidos_lag_1', 'pedidos_lag_2', 'pedidos_lag_3', 'pedidos_lag_4',
        'pedidos_lag_5', 'pedidos_lag_6', 'pedidos_lag_7', 'pedidos_lag_8',
        'pedidos_lag_9', 'pedidos_lag_10', 'pedidos_lag_11', 'pedidos_lag_12',
        'pedidos_lag_13', 'pedidos_lag_14', 'pedidos_weekday_lag_1',
        'pedidos_weekday_lag_2', 'pedidos_weekday_lag_3', 'pedidos_rolling_2',
        'pedidos_rolling_7', 'pedidos_prev_week_avg', 'pedidos_dow_avg_2wks',
        'pedidos_dow_avg_3wks', 'stl_trend_lag_1', 'stl_trend_lag_2',
        'stl_trend_lag_3', 'stl_trend_lag_4', 'stl_trend_lag_5',
        'stl_trend_lag_6', 'stl_trend_lag_7', 'stl_trend_lag_8',
        'stl_trend_lag_9', 'stl_trend_lag_10', 'stl_trend_lag_11',
        'stl_trend_lag_12', 'stl_trend_lag_13', 'stl_trend_lag_14',
        'stl_seasonal_lag_1', 'stl_seasonal_lag_2', 'stl_seasonal_lag_3',
        'stl_seasonal_lag_4', 'stl_seasonal_lag_5', 'stl_seasonal_lag_6',
        'stl_seasonal_lag_7', 'stl_seasonal_lag_8', 'stl_seasonal_lag_9',
        'stl_seasonal_lag_10', 'stl_seasonal_lag_11', 'stl_seasonal_lag_12',
        'stl_seasonal_lag_13', 'stl_seasonal_lag_14'],
       dtype='object'))

In [21]:
df

,fecha,sku,pedidos,day_of_week,day_of_month,is_weekend,week_of_month,is_start_of_month,is_near_quincena,is_vacation,pedidos_lag_1,pedidos_lag_2,pedidos_lag_3,pedidos_lag_4,pedidos_lag_5,pedidos_lag_6,pedidos_lag_7,pedidos_lag_8,pedidos_lag_9,pedidos_lag_10,pedidos_lag_11,pedidos_lag_12,pedidos_lag_13,pedidos_lag_14,pedidos_weekday_lag_1,pedidos_weekday_lag_2,pedidos_weekday_lag_3,pedidos_rolling_2,pedidos_rolling_7,pedidos_prev_week_avg,pedidos_dow_avg_2wks,pedidos_dow_avg_3wks,stl_trend_lag_1,stl_trend_lag_2,stl_trend_lag_3,stl_trend_lag_4,stl_trend_lag_5,stl_trend_lag_6,stl_trend_lag_7,stl_trend_lag_8,stl_trend_lag_9,stl_trend_lag_10,stl_trend_lag_11,stl_trend_lag_12,stl_trend_lag_13,stl_trend_lag_14,stl_seasonal_lag_1,stl_seasonal_lag_2,stl_seasonal_lag_3,stl_seasonal_lag_4,stl_seasonal_lag_5,stl_seasonal_lag_6,stl_seasonal_lag_7,stl_seasonal_lag_8,stl_seasonal_lag_9,stl_seasonal_lag_10,stl_seasonal_lag_11,stl_seasonal_lag_12,stl_seasonal_lag_13,stl_seasonal_lag_14
21,2024-07-26,SKU1,0.0,4,26,0,4,0,0,1,30000.0,54000.0,6000.0,6000.0,6000.0,3000.0,6000.0,30000.0,36000.0,2400.0,2400.0,2400.0,0.0,0.0,6000.0,0.0,7200.0,42000.0,15857.142857,13200.000000,6000.0,6600.0,11912.075530,12067.577030,12245.869160,12505.547013,12750.034828,12822.162603,12637.629174,12266.527681,11860.325068,11553.859386,11318.073301,11162.328801,11142.505288,11307.379638,18847.399955,21172.839407,-7645.745853,-7408.951414,-6810.414165,-9948.694610,-9241.110114,23936.177946,17935.030019,-8482.941590,-8702.020679,-7241.913414,-9376.524091,-9032.297251
22,2024-07-27,SKU1,0.0,5,27,1,4,0,0,1,0.0,30000.0,54000.0,6000.0,6000.0,6000.0,3000.0,6000.0,30000.0,36000.0,2400.0,2400.0,2400.0,0.0,3000.0,0.0,7200.0,30000.0,17500.000000,11742.857143,3000.0,5100.0,11781.079855,11912.075530,12067.577030,12245.869160,12505.547013,12750.034828,12822.162603,12637.629174,12266.527681,11860.325068,11553.859386,11318.073301,11162.328801,11142.505288,-9310.776185,18847.399955,21172.839407,-7645.745853,-7408.951414,-6810.414165,-9948.694610,-9241.110114,23936.177946,17935.030019,-8482.941590,-8702.020679,-7241.913414,-9376.524091
24,2024-07-29,SKU1,6000.0,0,29,0,5,0,1,1,6000.0,0.0,0.0,30000.0,54000.0,6000.0,6000.0,6000.0,3000.0,6000.0,30000.0,36000.0,2400.0,2400.0,6000.0,2400.0,3000.0,6000.0,20400.000000,12771.428571,4200.0,3800.0,11759.561758,11686.683023,11781.079855,11912.075530,12067.577030,12245.869160,12505.547013,12750.034828,12822.162603,12637.629174,12266.527681,11860.325068,11553.859386,11318.073301,-6275.247195,-10356.559802,-9310.776185,18847.399955,21172.839407,-7645.745853,-7408.951414,-6810.414165,-9948.694610,-9241.110114,23936.177946,17935.030019,-8482.941590,-8702.020679
25,2024-07-30,SKU1,6000.0,1,30,0,5,0,1,1,6000.0,6000.0,0.0,0.0,30000.0,54000.0,6000.0,6000.0,6000.0,3000.0,6000.0,30000.0,36000.0,2400.0,6000.0,2400.0,3000.0,6000.0,20400.000000,13285.714286,4200.0,3800.0,12147.310782,11759.561758,11686.683023,11781.079855,11912.075530,12067.577030,12245.869160,12505.547013,12750.034828,12822.162603,12637.629174,12266.527681,11860.325068,11553.859386,-6213.341647,-6275.247195,-10356.559802,-9310.776185,18847.399955,21172.839407,-7645.745853,-7408.951414,-6810.414165,-9948.694610,-9241.110114,23936.177946,17935.030019,-8482.941590
26,2024-07-31,SKU1,36000.0,2,31,0,5,0,1,1,6000.0,6000.0,6000.0,0.0,0.0,30000.0,54000.0,6000.0,6000.0,6000.0,3000.0,6000.0,30000.0,36000.0,54000.0,36000.0,24000.0,6000.0,20400.000000,15857.142857,45000.0,38000.0,12733.007654,12147.310782,11759.561758,11686.683023,11781.079855,11912.075530,12067.577030,12245.869160,12505.547013,12750.034828,12822.162603,12637.629174,12266.527681,11860.325068,-6884.697557,-6213.341647,-6275.247195,-10356.559802,-9310.776185,18847.399955,21172.839407,-7645.745853,-7408.951414,-6810.414165,-9948.694610,-9241.110114,23936.177946,17935.030019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7275,2025-04-06,SKU9,420.0,6,6,1,1,0,0,0,1680.0,0.0,420.0,600.0,1680.0,2640.0,1500.0,2400.0,3000.0,2400.0,2400.0,600.0,1200.0,300.0,1500.0,300.0,0.0,1680.0,1420.000000,1928.571429,900.0,900.0,1636.469530,1650.681594,1674.301657,1729.551031,1770.667182,1795.004961,1811.233599,1800.735270,1778.602081,1738.945772,1665.081511,1543.904147,1411.214364,1284.893101,265.135836,1769.985087,-1212.290342,959.894897,-17.891712,-339.004356,-1053.742183,85.983031,1108.658159,-904.380206,796.501608,409.168322,-212.799901,-911.107120
7276,2025-04-07,SKU9,1200.0,0,7,0,1,0,0,0,420.0,1680.0,0.0,420.0,600.0,1680.0,2640.0,1500.0,2400.0,3000.0,2400.0,2400.0,600.0,1200.0,2640.0,1200.0,378.0,1050.0,1240.000000,2134.285714,1920.0,1406.0,1626.805279,1636.469530,1650.681594,1674.301657,1729.551031,1770.667182,1795.004961,1811.233599,1800.735270,1778.602081,1738.945772,1665.081511,1543.904147,1411.214364,-1196.517491,265.135836,1769.985087,-1212.290342,959.894897,-17.891712,-339.004356,-1053.742183,85.983031,1108.658159,-904.380206,796.501608,409.168322,-212.799901
7277,2025-04-08,SKU9,1200.0,1,8,0,2,0,0,0,1200.0,420.0,1680.0,0.0,420.0,600.0,1680.0,2640.0,1500.0,2400.0,3000.0,2400.0,2400.0,600.0,1680.0,600.0,6000.0,810.0,1000.000000,2288.571429,1140.0,2760.0,1620.689016,1626.805279,1636.469530,1650.681594,1674.301657,1729.551031,1770.667182,1795.004961,1811.233599,1800.735270,1778.602081,1738.945772,1665.081511,1543.904147,-459.282296,-1196.517491,265.135836,1769.985087,-1212.290342,959.894897,-17.891712,-339.004356,-1053.742183,85.983031,1108.658159,-904.380206,796.501608,409.168322
7278,2025-04-09,SKU9,1800.0,2,9,0,2,0,0,0,1200.0,1200.0,420.0,1680.0,0.0,420.0,600.0,1680.0,2640.0,1500.0,2400.0,3000.0,2400.0,2400.0,600.0,2400.0,3000.0,1200.0,920.000000,2031.428571,1500.0,2000.0,1617.680712,1620.689016,1626.805279,1636.469530,1650.681594,1674.301657,1729.551031,1770.667182,1795.004961,1811.233599,1800.735270,1778.602081,1738.945772,1665.081511,-451.022952,-459.282296,-1196.517491,265.135836,1769.985087,-1212.290342,959.894897,-17.891712,-339.004356,-1053.742183,85.983031,1108.658159,-904.380206,796.501608
7279,2025-04-10,SKU9,120.0,3,10,0,2,0,0,0,2760.0,1200.0,1200.0,420.0,1680.0,0.0,420.0,600.0,1680.0,2640.0,1500.0,2400.0,3000.0,2400.0,420.0,2400.0,300.0,1980.0,1280.000000,1748.571429,1410.0,1040.0,1617.300605,1617.680712,1620.689016,1626.805279,1636.469530,1650.681594,1674.301657,1729.551031,1770.667182,1795.004961,1811.233599,1800.735270,1778.602081,1738.945772,1131.362621,-451.022952,-459.282296,-1196.517491,265.135836,1769.985087,-1212.290342,959.894897,-17.891712,-339.004356,-1053.742183,85.983031,1108.658159,-904.380206

# Modelling

In [22]:
## Preparación de data para modelling

# Separamos el conjunto de datos en entrenamiento y prueba, usando los últimos 7 días como prueba
test = df.tail(7)
df_mod = df[:-7].copy()

# Identificamos las variables predictoras
features = df_mod.columns.difference(["fecha", "sku", "pedidos"]).to_list()

# definimos el numero de ventanas de evaluación y el tamaño de las ventanas
val_iter = 3
val_size = 7

## Evaluación modelos XGBoost

In [23]:
# Creamos un DataFrame para almacenar los resultados de cada SKU
# Este DataFrame contendrá el SKU, los parámetros del modelo y las métricas de evaluación
##########

results = []

for sku in df_mod["sku"].unique():
    print("\n-----------------------")
    print(f"\n🔍 Optimizando para SKU: {sku}\n")

    # Filtramos el DataFrame para el SKU actual
    df_sku = df_mod[df_mod["sku"] == sku].copy()

    # Calculamos el tamaño del conjunto de entrenamiento
    train_size = df_sku.shape[0] - val_iter * val_size

    # Definimos el espacio de búsqueda de hiperparámetros para el modelo XGBoost
    # Usamos funciones lambda para que Optuna pueda sugerir valores
    param_grid = {
        "max_depth": lambda trial: trial.suggest_int("max_depth", 1, 5, step=1),
        "learning_rate": lambda trial: trial.suggest_float(
            "learning_rate", 0.001, 0.1, step=0.001
        ),
        "n_estimators": lambda trial: trial.suggest_int(
            "n_estimators", 50, 3000, step=50
        ),
        "subsample": lambda trial: trial.suggest_float(
            "subsample", 0.5, 1.0, step=0.02
        ),
        "colsample_bytree": lambda trial: trial.suggest_float(
            "colsample_bytree", 0.5, 1.0, step=0.02
        ),
        "gamma": lambda trial: trial.suggest_float("gamma", 1, 30, step=0.5),
        "reg_alpha": lambda trial: trial.suggest_float("reg_alpha", 1, 30, step=0.5),
        "reg_lambda": lambda trial: trial.suggest_float("reg_lambda", 1, 30, step=0.5),
        "min_child_weight": lambda trial: trial.suggest_int(
            "min_child_weight", 5, 20, step=1
        ),
        "random_state": lambda trial: 100,  # Fijamos la semilla para reproducibilidad
    }

    # Optimizamos el modelo XGBoost usando Optuna con ventana recursiva
    study = ml_utils.optimize_model_with_optuna(
        model_class=XGBRegressor,
        param_grid=param_grid,
        X=df_sku[features],
        y=df_sku["pedidos"],
        n_trials=125,
        val_iter=val_iter,
        train_size=train_size,
        val_size=val_size,
        show_progress_bar=True,
    )

    # Obtenemos el mejor trial del estudio
    # y almacenamos los resultados en un diccionario
    best_trial = study.best_trials[0]
    results.append(
        {
            "sku": sku,
            "study": study,
            "best_params": best_trial.params,
            "best_smape": best_trial.values[0],
            "best_gap": best_trial.values[1],
            "model": "XGBRegressor",
            "n_trials": len(study.trials),
        }
    )

    print("\n-----------------------")


df_results_xgboost = pd.DataFrame(results)

-----------------------

🔍 Optimizando para SKU: SKU1

  0%|          | 0/125 [00:00<?, ?it/s]

100%|██████████| 125/125 [10:36<00:00,  5.10s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 27.4600, GAP: 1.8300
Trial 1 - SMAPE: 27.4400, GAP: 3.9200
Trial 2 - SMAPE: 29.0000, GAP: 1.7000
Trial 3 - SMAPE: 27.0400, GAP: 5.3700
Trial 4 - SMAPE: 26.7900, GAP: 6.5500

Número total de Best Trials ('Frente de pareto'): 5

🏆 Best Trial Params:
{'max_depth': 2, 'learning_rate': 0.021, 'n_estimators': 2800, 'subsample': 0.9, 'colsample_bytree': 0.98, 'gamma': 2.0, 'reg_alpha': 5.0, 'reg_lambda': 6.5, 'min_child_weight': 6}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU10

100%|██████████| 125/125 [05:52<00:00,  2.82s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 25.8400, GAP: 3.7800
Trial 1 - SMAPE: 26.8300, GAP: 1.3000
Trial 2 - SMAPE: 26.5100, GAP: 3.3800
Trial 3 - SMAPE: 23.9100, GAP: 3.8800

Número total de Best Trials ('Frente de pareto'): 4

🏆 Best Trial Params:
{'max_depth': 5, 'learning_rate': 0.076, 'n_estimators': 100, 'subsample': 0.58, 'colsample_bytree': 0.66, 'gamma': 1.0, 'reg_alpha': 21.0, 'reg_lambda': 24.5, 'min_child_weight': 16}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU11

100%|██████████| 125/125 [06:09<00:00,  2.96s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 35.7700, GAP: 3.8600
Trial 1 - SMAPE: 34.4300, GAP: 6.0800
Trial 2 - SMAPE: 34.9900, GAP: 4.0900
Trial 3 - SMAPE: 34.9100, GAP: 4.1100
Trial 4 - SMAPE: 42.8500, GAP: 2.7200

Número total de Best Trials ('Frente de pareto'): 15

🏆 Best Trial Params:
{'max_depth': 1, 'learning_rate': 0.001, 'n_estimators': 2700, 'subsample': 0.58, 'colsample_bytree': 0.9199999999999999, 'gamma': 20.0, 'reg_alpha': 13.5, 'reg_lambda': 24.5, 'min_child_weight': 20}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU12

100%|██████████| 125/125 [03:47<00:00,  1.82s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 78.9600, GAP: 23.5900
Trial 1 - SMAPE: 70.4900, GAP: 26.4500
Trial 2 - SMAPE: 80.0700, GAP: 23.0800
Trial 3 - SMAPE: 67.6600, GAP: 28.0200
Trial 4 - SMAPE: 69.2400, GAP: 27.9100

Número total de Best Trials ('Frente de pareto'): 11

🏆 Best Trial Params:
{'max_depth': 3, 'learning_rate': 0.009000000000000001, 'n_estimators': 50, 'subsample': 0.8400000000000001, 'colsample_bytree': 0.78, 'gamma': 14.5, 'reg_alpha': 18.5, 'reg_lambda': 8.5, 'min_child_weight': 13}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU13

100%|██████████| 125/125 [03:32<00:00,  1.70s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 46.8200, GAP: 13.1000
Trial 1 - SMAPE: 46.7700, GAP: 13.2200
Trial 2 - SMAPE: 46.4900, GAP: 14.2600
Trial 3 - SMAPE: 46.0300, GAP: 14.5800
Trial 4 - SMAPE: 43.8100, GAP: 16.6900

Número total de Best Trials ('Frente de pareto'): 15

🏆 Best Trial Params:
{'max_depth': 4, 'learning_rate': 0.058, 'n_estimators': 50, 'subsample': 0.7, 'colsample_bytree': 0.72, 'gamma': 22.5, 'reg_alpha': 29.0, 'reg_lambda': 18.5, 'min_child_weight': 15}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU14

100%|██████████| 125/125 [09:07<00:00,  4.38s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 34.8400, GAP: 14.8200
Trial 1 - SMAPE: 35.9700, GAP: 13.7500
Trial 2 - SMAPE: 36.4500, GAP: 12.9300
Trial 3 - SMAPE: 34.2200, GAP: 14.8600
Trial 4 - SMAPE: 36.3600, GAP: 13.2600

Número total de Best Trials ('Frente de pareto'): 5

🏆 Best Trial Params:
{'max_depth': 1, 'learning_rate': 0.063, 'n_estimators': 3000, 'subsample': 0.62, 'colsample_bytree': 0.74, 'gamma': 26.0, 'reg_alpha': 7.0, 'reg_lambda': 10.5, 'min_child_weight': 14}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU15

100%|██████████| 125/125 [08:15<00:00,  3.96s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 43.3600, GAP: 20.5700
Trial 1 - SMAPE: 46.8200, GAP: 19.6400

Número total de Best Trials ('Frente de pareto'): 2

🏆 Best Trial Params:
{'max_depth': 3, 'learning_rate': 0.028, 'n_estimators': 2700, 'subsample': 0.52, 'colsample_bytree': 0.7, 'gamma': 10.0, 'reg_alpha': 5.0, 'reg_lambda': 27.5, 'min_child_weight': 19}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU16

100%|██████████| 125/125 [06:27<00:00,  3.10s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 22.3900, GAP: 9.3800
Trial 1 - SMAPE: 21.3700, GAP: 11.4300
Trial 2 - SMAPE: 20.9200, GAP: 14.0000
Trial 3 - SMAPE: 21.8400, GAP: 9.7400
Trial 4 - SMAPE: 21.2300, GAP: 13.6700

Número total de Best Trials ('Frente de pareto'): 8

🏆 Best Trial Params:
{'max_depth': 1, 'learning_rate': 0.07200000000000001, 'n_estimators': 2050, 'subsample': 0.76, 'colsample_bytree': 0.54, 'gamma': 25.0, 'reg_alpha': 3.0, 'reg_lambda': 30.0, 'min_child_weight': 9}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU17

100%|██████████| 125/125 [04:44<00:00,  2.28s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 32.0400, GAP: 4.5800
Trial 1 - SMAPE: 32.0600, GAP: 4.0300
Trial 2 - SMAPE: 33.4300, GAP: 3.6900
Trial 3 - SMAPE: 29.9000, GAP: 5.1300
Trial 4 - SMAPE: 30.6800, GAP: 4.7000

Número total de Best Trials ('Frente de pareto'): 7

🏆 Best Trial Params:
{'max_depth': 1, 'learning_rate': 0.08, 'n_estimators': 650, 'subsample': 0.5, 'colsample_bytree': 0.98, 'gamma': 6.0, 'reg_alpha': 17.5, 'reg_lambda': 3.0, 'min_child_weight': 11}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU18

100%|██████████| 125/125 [52:25<00:00, 25.17s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 45.6600, GAP: 18.5000
Trial 1 - SMAPE: 47.4700, GAP: 14.4800
Trial 2 - SMAPE: 46.4500, GAP: 16.0300
Trial 3 - SMAPE: 41.4300, GAP: 23.4300
Trial 4 - SMAPE: 46.0000, GAP: 16.9900

Número total de Best Trials ('Frente de pareto'): 7

🏆 Best Trial Params:
{'max_depth': 1, 'learning_rate': 0.053000000000000005, 'n_estimators': 150, 'subsample': 0.6799999999999999, 'colsample_bytree': 1.0, 'gamma': 30.0, 'reg_alpha': 25.5, 'reg_lambda': 1.0, 'min_child_weight': 7}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU19

100%|██████████| 125/125 [1:49:19<00:00, 52.47s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 74.3100, GAP: 32.9300
Trial 1 - SMAPE: 64.2800, GAP: 33.9300
Trial 2 - SMAPE: 64.8800, GAP: 33.5500
Trial 3 - SMAPE: 65.1100, GAP: 33.4900
Trial 4 - SMAPE: 78.9500, GAP: 29.8000

Número total de Best Trials ('Frente de pareto'): 6

🏆 Best Trial Params:
{'max_depth': 2, 'learning_rate': 0.054, 'n_estimators': 50, 'subsample': 0.96, 'colsample_bytree': 0.96, 'gamma': 16.5, 'reg_alpha': 18.5, 'reg_lambda': 5.5, 'min_child_weight': 17}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU2

100%|██████████| 125/125 [21:05<00:00, 10.13s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 24.8100, GAP: 12.5600
Trial 1 - SMAPE: 24.7700, GAP: 16.3300
Trial 2 - SMAPE: 24.8200, GAP: 9.8800
Trial 3 - SMAPE: 25.3400, GAP: 6.6800
Trial 4 - SMAPE: 28.3200, GAP: 2.4800

Número total de Best Trials ('Frente de pareto'): 14

🏆 Best Trial Params:
{'max_depth': 5, 'learning_rate': 0.02, 'n_estimators': 1350, 'subsample': 0.54, 'colsample_bytree': 0.8, 'gamma': 1.0, 'reg_alpha': 14.5, 'reg_lambda': 16.0, 'min_child_weight': 19}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU20

100%|██████████| 125/125 [04:18<00:00,  2.07s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 63.2000, GAP: 30.3300
Trial 1 - SMAPE: 66.3600, GAP: 27.3700
Trial 2 - SMAPE: 70.8800, GAP: 23.0600
Trial 3 - SMAPE: 64.6700, GAP: 28.4000
Trial 4 - SMAPE: 62.9600, GAP: 33.2500

Número total de Best Trials ('Frente de pareto'): 13

🏆 Best Trial Params:
{'max_depth': 1, 'learning_rate': 0.083, 'n_estimators': 650, 'subsample': 0.98, 'colsample_bytree': 0.72, 'gamma': 16.5, 'reg_alpha': 17.0, 'reg_lambda': 1.0, 'min_child_weight': 11}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU21

100%|██████████| 125/125 [08:19<00:00,  3.99s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 27.6200, GAP: 4.1200
Trial 1 - SMAPE: 27.6900, GAP: 2.5400

Número total de Best Trials ('Frente de pareto'): 2

🏆 Best Trial Params:
{'max_depth': 1, 'learning_rate': 0.017, 'n_estimators': 2650, 'subsample': 0.98, 'colsample_bytree': 0.74, 'gamma': 13.5, 'reg_alpha': 9.0, 'reg_lambda': 3.5, 'min_child_weight': 6}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU22

100%|██████████| 125/125 [04:21<00:00,  2.09s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 36.4800, GAP: 4.5900
Trial 1 - SMAPE: 33.9100, GAP: 8.0400
Trial 2 - SMAPE: 36.4600, GAP: 4.9000
Trial 3 - SMAPE: 37.6800, GAP: 4.5300
Trial 4 - SMAPE: 33.5100, GAP: 8.3600

Número total de Best Trials ('Frente de pareto'): 8

🏆 Best Trial Params:
{'max_depth': 1, 'learning_rate': 0.065, 'n_estimators': 500, 'subsample': 0.86, 'colsample_bytree': 0.8200000000000001, 'gamma': 19.0, 'reg_alpha': 22.0, 'reg_lambda': 1.0, 'min_child_weight': 16}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU23

100%|██████████| 125/125 [04:32<00:00,  2.18s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 27.8200, GAP: 7.8800
Trial 1 - SMAPE: 27.6800, GAP: 9.5600
Trial 2 - SMAPE: 26.2300, GAP: 9.7900
Trial 3 - SMAPE: 26.3100, GAP: 9.6800

Número total de Best Trials ('Frente de pareto'): 4

🏆 Best Trial Params:
{'max_depth': 1, 'learning_rate': 0.066, 'n_estimators': 150, 'subsample': 0.76, 'colsample_bytree': 0.96, 'gamma': 23.5, 'reg_alpha': 28.5, 'reg_lambda': 4.5, 'min_child_weight': 15}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU24

100%|██████████| 125/125 [07:32<00:00,  3.62s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 47.5600, GAP: 6.7200
Trial 1 - SMAPE: 44.2000, GAP: 7.9100
Trial 2 - SMAPE: 44.5900, GAP: 7.0500
Trial 3 - SMAPE: 42.4000, GAP: 8.5900
Trial 4 - SMAPE: 36.0700, GAP: 18.3200

Número total de Best Trials ('Frente de pareto'): 10

🏆 Best Trial Params:
{'max_depth': 2, 'learning_rate': 0.001, 'n_estimators': 400, 'subsample': 0.66, 'colsample_bytree': 0.72, 'gamma': 1.0, 'reg_alpha': 27.5, 'reg_lambda': 6.0, 'min_child_weight': 14}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU25

100%|██████████| 125/125 [04:56<00:00,  2.37s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 43.3500, GAP: 2.3400
Trial 1 - SMAPE: 43.3300, GAP: 2.5800
Trial 2 - SMAPE: 40.0900, GAP: 2.7200
Trial 3 - SMAPE: 41.2200, GAP: 2.7100
Trial 4 - SMAPE: 39.4400, GAP: 3.3100

Número total de Best Trials ('Frente de pareto'): 5

🏆 Best Trial Params:
{'max_depth': 1, 'learning_rate': 0.078, 'n_estimators': 50, 'subsample': 1.0, 'colsample_bytree': 0.5, 'gamma': 30.0, 'reg_alpha': 24.5, 'reg_lambda': 30.0, 'min_child_weight': 6}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU26

100%|██████████| 125/125 [07:41<00:00,  3.70s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 35.7800, GAP: 6.6400
Trial 1 - SMAPE: 34.7000, GAP: 7.0300
Trial 2 - SMAPE: 32.6300, GAP: 8.1300
Trial 3 - SMAPE: 33.9200, GAP: 7.5100
Trial 4 - SMAPE: 32.9200, GAP: 7.6800

Número total de Best Trials ('Frente de pareto'): 6

🏆 Best Trial Params:
{'max_depth': 1, 'learning_rate': 0.009000000000000001, 'n_estimators': 2650, 'subsample': 0.7, 'colsample_bytree': 0.56, 'gamma': 30.0, 'reg_alpha': 2.0, 'reg_lambda': 19.0, 'min_child_weight': 14}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU3

100%|██████████| 125/125 [05:16<00:00,  2.53s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 25.5300, GAP: 9.0400
Trial 1 - SMAPE: 31.3100, GAP: 6.4600
Trial 2 - SMAPE: 29.6400, GAP: 8.1800
Trial 3 - SMAPE: 30.3600, GAP: 7.2600
Trial 4 - SMAPE: 30.4800, GAP: 7.1400

Número total de Best Trials ('Frente de pareto'): 14

🏆 Best Trial Params:
{'max_depth': 2, 'learning_rate': 0.016, 'n_estimators': 750, 'subsample': 1.0, 'colsample_bytree': 0.72, 'gamma': 22.0, 'reg_alpha': 8.0, 'reg_lambda': 17.0, 'min_child_weight': 5}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU4

100%|██████████| 125/125 [04:57<00:00,  2.38s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 20.5700, GAP: 6.0200
Trial 1 - SMAPE: 22.8100, GAP: 3.8400
Trial 2 - SMAPE: 19.3000, GAP: 8.4100
Trial 3 - SMAPE: 18.6000, GAP: 9.3000
Trial 4 - SMAPE: 17.5000, GAP: 14.6100

Número total de Best Trials ('Frente de pareto'): 14

🏆 Best Trial Params:
{'max_depth': 4, 'learning_rate': 0.017, 'n_estimators': 650, 'subsample': 0.5, 'colsample_bytree': 0.72, 'gamma': 20.5, 'reg_alpha': 18.5, 'reg_lambda': 13.5, 'min_child_weight': 15}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU5

100%|██████████| 125/125 [06:46<00:00,  3.25s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 16.1400, GAP: 11.9700
Trial 1 - SMAPE: 16.2100, GAP: 9.2400
Trial 2 - SMAPE: 16.4000, GAP: 7.9700
Trial 3 - SMAPE: 16.7100, GAP: 6.9500

Número total de Best Trials ('Frente de pareto'): 4

🏆 Best Trial Params:
{'max_depth': 3, 'learning_rate': 0.095, 'n_estimators': 1900, 'subsample': 0.6799999999999999, 'colsample_bytree': 0.8400000000000001, 'gamma': 23.5, 'reg_alpha': 14.5, 'reg_lambda': 23.5, 'min_child_weight': 8}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU6

100%|██████████| 125/125 [05:07<00:00,  2.46s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 36.2500, GAP: 12.7800
Trial 1 - SMAPE: 38.0000, GAP: 12.4600
Trial 2 - SMAPE: 36.6700, GAP: 12.5200
Trial 3 - SMAPE: 38.7900, GAP: 12.1400
Trial 4 - SMAPE: 39.9700, GAP: 12.1300

Número total de Best Trials ('Frente de pareto'): 6

🏆 Best Trial Params:
{'max_depth': 1, 'learning_rate': 0.001, 'n_estimators': 1500, 'subsample': 0.9, 'colsample_bytree': 0.54, 'gamma': 25.0, 'reg_alpha': 10.0, 'reg_lambda': 12.5, 'min_child_weight': 8}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU7

100%|██████████| 125/125 [04:31<00:00,  2.17s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 47.1100, GAP: 8.0500
Trial 1 - SMAPE: 48.1800, GAP: 7.4900
Trial 2 - SMAPE: 48.4300, GAP: 6.7000
Trial 3 - SMAPE: 41.0500, GAP: 10.5100
Trial 4 - SMAPE: 46.9900, GAP: 8.4300

Número total de Best Trials ('Frente de pareto'): 10

🏆 Best Trial Params:
{'max_depth': 1, 'learning_rate': 0.002, 'n_estimators': 900, 'subsample': 0.98, 'colsample_bytree': 0.78, 'gamma': 19.0, 'reg_alpha': 1.0, 'reg_lambda': 17.5, 'min_child_weight': 5}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU8

100%|██████████| 125/125 [04:07<00:00,  1.98s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 86.8800, GAP: 32.1800
Trial 1 - SMAPE: 88.0000, GAP: 30.9700
Trial 2 - SMAPE: 86.6300, GAP: 33.9200
Trial 3 - SMAPE: 85.7000, GAP: 34.3600
Trial 4 - SMAPE: 85.5000, GAP: 34.3700

Número total de Best Trials ('Frente de pareto'): 16

🏆 Best Trial Params:
{'max_depth': 1, 'learning_rate': 0.005, 'n_estimators': 800, 'subsample': 0.94, 'colsample_bytree': 0.88, 'gamma': 18.0, 'reg_alpha': 23.0, 'reg_lambda': 2.5, 'min_child_weight': 19}

-----------------------

-----------------------

🔍 Optimizando para SKU: SKU9

100%|██████████| 125/125 [04:49<00:00,  2.31s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 59.7900, GAP: 41.2700
Trial 1 - SMAPE: 61.7200, GAP: 38.6600
Trial 2 - SMAPE: 62.8000, GAP: 19.1100
Trial 3 - SMAPE: 60.2200, GAP: 40.3000
Trial 4 - SMAPE: 63.1500, GAP: 18.3200

Número total de Best Trials ('Frente de pareto'): 7

🏆 Best Trial Params:
{'max_depth': 2, 'learning_rate': 0.065, 'n_estimators': 1300, 'subsample': 1.0, 'colsample_bytree': 0.86, 'gamma': 21.0, 'reg_alpha': 17.0, 'reg_lambda': 14.0, 'min_child_weight': 7}

-----------------------

In [24]:
df_results_xgboost

,sku,study,best_params,best_smape,best_gap,model,n_trials
0,SKU1,<optuna.study.study.Study object at 0x1380c0ad0>,"{'max_depth': 2, 'learning_rate': 0.021, 'n_es...",27.46,1.83,XGBRegressor,125
1,SKU10,<optuna.study.study.Study object at 0x1380634d0>,"{'max_depth': 5, 'learning_rate': 0.076, 'n_es...",25.84,3.78,XGBRegressor,125
2,SKU11,<optuna.study.study.Study object at 0x138063b10>,"{'max_depth': 1, 'learning_rate': 0.001, 'n_es...",35.77,3.86,XGBRegressor,125
3,SKU12,<optuna.study.study.Study object at 0x12fd3b490>,"{'max_depth': 3, 'learning_rate': 0.0090000000...",78.96,23.59,XGBRegressor,125
4,SKU13,<optuna.study.study.Study object at 0x1380ac8a0>,"{'max_depth': 4, 'learning_rate': 0.058, 'n_es...",46.82,13.10,XGBRegressor,125
5,SKU14,<optuna.study.study.Study object at 0x1380fa0f0>,"{'max_depth': 1, 'learning_rate': 0.063, 'n_es...",34.84,14.82,XGBRegressor,125
6,SKU15,<optuna.study.study.Study object at 0x138029040>,"{'max_depth': 3, 'learning_rate': 0.028, 'n_es...",43.36,20.57,XGBRegressor,125
7,SKU16,<optuna.study.study.Study object at 0x1380298c0>,"{'max_depth': 1, 'learning_rate': 0.0720000000...",22.39,9.38,XGBRegressor,125
8,SKU17,<optuna.study.study.Study object at 0x12fd5bb50>,"{'max_depth': 1, 'learning_rate': 0.08, 'n_est...",32.04,4.58,XGBRegressor,125
9,SKU18,<optuna.study.study.Study object at 0x139208650>,"{'max_depth': 1, 'learning_rate': 0.0530000000...",45.66,18.50,XGBRegressor,125
10,SKU19,<optuna.study.study.Study object at 0x12fd53b60>,"{'max_depth': 2, 'learning_rate': 0.054, 'n_es...",74.31,32.93,XGBRegressor,125
11,SKU2,<optuna.study.study.Study object at 0x138464320>,"{'max_depth': 5, 'learning_rate': 0.02, 'n_est...",24.81,12.56,XGBRegressor,125
12,SKU20,<optuna.study.study.Study object at 0x1380a2190>,"{'max_depth': 1, 'learning_rate': 0.083, 'n_es...",63.20,30.33,XGBRegressor,125
13,SKU21,<optuna.study.study.Study object at 0x1380a2970>,"{'max_depth': 1, 'learning_rate': 0.017, 'n_es...",27.62,4.12,XGBRegressor,125
14,SKU22,<optuna.study.study.Study object at 0x1397064e0>,"{'max_depth': 1, 'learning_rate': 0.065, 'n_es...",36.48,4.59,XGBRegressor,125
15,SKU23,<optuna.study.study.Study object at 0x13806ed50>,"{'max_depth': 1, 'learning_rate': 0.066, 'n_es...",27.82,7.88,XGBRegressor,125
16,SKU24,<optuna.study.study.Study object at 0x13806f350>,"{'max_depth': 2, 'learning_rate': 0.001, 'n_es...",47.56,6.72,XGBRegressor,125
17,SKU25,<optuna.study.study.Study object at 0x13993b8b0>,"{'max_depth': 1, 'learning_rate': 0.078, 'n_es...",43.35,2.34,XGBRegressor,125
18,SKU26,<optuna.study.study.Study object at 0x1399afc20>,"{'max_depth': 1, 'learning_rate': 0.0090000000...",35.78,6.64,XGBRegressor,125
19,SKU3,<optuna.study.study.Study object at 0x13809e5d0>,"{'max_depth': 2, 'learning_rate': 0.016, 'n_es...",25.53,9.04,XGBRegressor,125
20,SKU4,<optuna.study.study.Study object at 0x1384dbbb0>,"{'max_depth': 4, 'learning_rate': 0.017, 'n_es...",20.57,6.02,XGBRegressor,125
21,SKU5,<optuna.study.study.Study object at 0x12fd5ec30>,"{'max_depth': 3, 'learning_rate': 0.095, 'n_es...",16.14,11.97,XGBRegressor,125
22,SKU6,<optuna.study.study.Study object at 0x12fd5f140>,"{'max_depth': 1, 'learning_rate': 0.001, 'n_es...",36.25,12.78,XGBRegressor,125
23,SKU7,<optuna.study.study.Study object at 0x12fd5e9f0>,"{'max_depth': 1, 'learning_rate': 0.002, 'n_es...",47.11,8.05,XGBRegressor,125
24,SKU8,<optuna.study.study.Study object at 0x12fd5f0b0>,"{'max_depth': 1, 'learning_rate': 0.005, 'n_es...",86.88,32.18,XGBRegressor,125
25,SKU9,<optuna.study.study.Study object at 0x12fd5ea80>,"{'max_depth': 2, 'learning_rate': 0.065, 'n_es...",59.79,41.27,XGBRegressor,125

In [25]:
## Mostrar graficas de Optuna por estudio especifico

# sku = "SKU1"
# temp = df_results_xgboost[df_results_xgboost["sku"] == sku].copy()
# plot_utils.mostrar_graficas_optuna(temp["study"], temp["model"])

## Evaluación modelos Random Forest

In [26]:
# Creamos un DataFrame para almacenar los resultados de cada SKU
# Este DataFrame contendrá el SKU, los parámetros del modelo y las métricas de evaluación
##########

results = []

for sku in df_mod["sku"].unique():
    print("\n-----------------------")
    print(f"🔍 Optimizando para SKU: {sku}\n")

    # Filtramos por SKU
    df_sku = df_mod[df_mod["sku"] == sku].copy()

    # Tamaño de entrenamiento
    train_size = df_sku.shape[0] - val_iter * val_size

    # Espacio de búsqueda de hiperparámetros para Random Forest
    param_grid = {
        "n_estimators": lambda trial: trial.suggest_int(
            "n_estimators", 50, 1000, step=50
        ),
        "max_depth": lambda trial: trial.suggest_int("max_depth", 1, 10, step=1),
        "min_samples_split": lambda trial: trial.suggest_int(
            "min_samples_split", 2, 10
        ),
        "min_samples_leaf": lambda trial: trial.suggest_int(
            "min_samples_leaf", 3, 15, step=1
        ),
        "max_features": lambda trial: trial.suggest_categorical(
            "max_features", ["sqrt", "log2", None]
        ),
        "bootstrap": lambda trial: trial.suggest_categorical(
            "bootstrap", [True, False]
        ),
        "random_state": lambda trial: 100,  # Fijamos el random_state para reproducibilidad
    }

    # Optimizamos usando tu función personalizada con modelo RandomForestRegressor
    study = ml_utils.optimize_model_with_optuna(
        model_class=RandomForestRegressor,
        param_grid=param_grid,
        X=df_sku[features],
        y=df_sku["pedidos"],
        n_trials=125,
        val_iter=val_iter,
        train_size=train_size,
        val_size=val_size,
        show_progress_bar=True,
    )

    # Registramos los resultados
    best_trial = study.best_trials[0]
    results.append(
        {
            "sku": sku,
            "study": study,
            "best_params": best_trial.params,
            "best_smape": best_trial.values[0],
            "best_gap": best_trial.values[1],
            "model": "RandomForestRegressor",
            "n_trials": len(study.trials),
        }
    )

    print("-----------------------")

# Creamos DataFrame con resultados
df_results_rf = pd.DataFrame(results)

-----------------------
🔍 Optimizando para SKU: SKU1

100%|██████████| 125/125 [05:10<00:00,  2.48s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 32.7100, GAP: 9.5900
Trial 1 - SMAPE: 36.5200, GAP: 6.3700
Trial 2 - SMAPE: 36.5200, GAP: 6.3700
Trial 3 - SMAPE: 35.9500, GAP: 8.3600
Trial 4 - SMAPE: 32.8700, GAP: 8.4700

Número total de Best Trials ('Frente de pareto'): 14

🏆 Best Trial Params:
{'n_estimators': 600, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': None, 'bootstrap': False}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU10

100%|██████████| 125/125 [04:54<00:00,  2.36s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 26.7000, GAP: 6.6200
Trial 1 - SMAPE: 28.5100, GAP: 1.1100
Trial 2 - SMAPE: 28.2100, GAP: 2.0600
Trial 3 - SMAPE: 27.3900, GAP: 5.7100
Trial 4 - SMAPE: 27.1700, GAP: 6.5300

Número total de Best Trials ('Frente de pareto'): 23

🏆 Best Trial Params:
{'n_estimators': 50, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 12, 'max_features': None, 'bootstrap': True}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU11

100%|██████████| 125/125 [02:53<00:00,  1.39s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 34.5800, GAP: 5.5300
Trial 1 - SMAPE: 42.8800, GAP: 4.6500
Trial 2 - SMAPE: 31.8000, GAP: 6.1400
Trial 3 - SMAPE: 39.3700, GAP: 5.4100
Trial 4 - SMAPE: 42.9000, GAP: 4.6400

Número total de Best Trials ('Frente de pareto'): 25

🏆 Best Trial Params:
{'n_estimators': 550, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': True}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU12

100%|██████████| 125/125 [02:46<00:00,  1.33s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 73.6900, GAP: 31.0600
Trial 1 - SMAPE: 73.6800, GAP: 31.1700
Trial 2 - SMAPE: 76.0300, GAP: 28.7600
Trial 3 - SMAPE: 75.6600, GAP: 28.9200
Trial 4 - SMAPE: 71.9600, GAP: 32.7000

Número total de Best Trials ('Frente de pareto'): 19

🏆 Best Trial Params:
{'n_estimators': 450, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': None, 'bootstrap': True}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU13

100%|██████████| 125/125 [04:13<00:00,  2.03s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 37.3800, GAP: 10.2800
Trial 1 - SMAPE: 33.9100, GAP: 12.4100
Trial 2 - SMAPE: 33.8700, GAP: 12.4200
Trial 3 - SMAPE: 49.4700, GAP: 8.8600
Trial 4 - SMAPE: 33.8700, GAP: 12.4200

Número total de Best Trials ('Frente de pareto'): 15

🏆 Best Trial Params:
{'n_estimators': 1000, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': False}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU14

100%|██████████| 125/125 [02:05<00:00,  1.00s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 64.5300, GAP: 25.7700
Trial 1 - SMAPE: 64.3100, GAP: 26.3500
Trial 2 - SMAPE: 58.6300, GAP: 31.1400
Trial 3 - SMAPE: 64.5300, GAP: 25.7700
Trial 4 - SMAPE: 58.3300, GAP: 31.4100

Número total de Best Trials ('Frente de pareto'): 34

🏆 Best Trial Params:
{'n_estimators': 200, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': True}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU15

100%|██████████| 125/125 [02:33<00:00,  1.23s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 50.7600, GAP: 14.5300
Trial 1 - SMAPE: 50.8100, GAP: 14.4700
Trial 2 - SMAPE: 50.7100, GAP: 14.5500
Trial 3 - SMAPE: 48.1000, GAP: 21.4400
Trial 4 - SMAPE: 48.5600, GAP: 21.3200

Número total de Best Trials ('Frente de pareto'): 9

🏆 Best Trial Params:
{'n_estimators': 600, 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': None, 'bootstrap': False}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU16

100%|██████████| 125/125 [02:57<00:00,  1.42s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 21.5100, GAP: 11.8200
Trial 1 - SMAPE: 21.8500, GAP: 11.4300
Trial 2 - SMAPE: 21.5600, GAP: 11.5900
Trial 3 - SMAPE: 20.9900, GAP: 13.3800
Trial 4 - SMAPE: 21.3400, GAP: 12.4800

Número total de Best Trials ('Frente de pareto'): 9

🏆 Best Trial Params:
{'n_estimators': 350, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': False}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU17

100%|██████████| 125/125 [03:13<00:00,  1.55s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 35.8800, GAP: 7.4400
Trial 1 - SMAPE: 36.2300, GAP: 6.8400
Trial 2 - SMAPE: 36.1000, GAP: 6.8800
Trial 3 - SMAPE: 46.1800, GAP: 5.9600
Trial 4 - SMAPE: 45.4800, GAP: 6.5300

Número total de Best Trials ('Frente de pareto'): 32

🏆 Best Trial Params:
{'n_estimators': 100, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': False}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU18

100%|██████████| 125/125 [02:58<00:00,  1.43s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 46.0200, GAP: 10.1100
Trial 1 - SMAPE: 46.0200, GAP: 10.1100

Número total de Best Trials ('Frente de pareto'): 2

🏆 Best Trial Params:
{'n_estimators': 800, 'max_depth': 1, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': False}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU19

100%|██████████| 125/125 [02:31<00:00,  1.21s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 67.5000, GAP: 23.7100
Trial 1 - SMAPE: 67.5000, GAP: 23.7100

Número total de Best Trials ('Frente de pareto'): 2

🏆 Best Trial Params:
{'n_estimators': 900, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 14, 'max_features': None, 'bootstrap': False}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU2

100%|██████████| 125/125 [03:03<00:00,  1.47s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 30.1800, GAP: 2.3000
Trial 1 - SMAPE: 30.1800, GAP: 2.3000
Trial 2 - SMAPE: 31.5200, GAP: 0.6400
Trial 3 - SMAPE: 29.4100, GAP: 8.5100
Trial 4 - SMAPE: 29.7400, GAP: 3.3700

Número total de Best Trials ('Frente de pareto'): 15

🏆 Best Trial Params:
{'n_estimators': 100, 'max_depth': 2, 'min_samples_split': 6, 'min_samples_leaf': 11, 'max_features': None, 'bootstrap': True}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU20

100%|██████████| 125/125 [03:44<00:00,  1.79s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 71.2400, GAP: 14.2900
Trial 1 - SMAPE: 71.2400, GAP: 14.2900
Trial 2 - SMAPE: 61.4900, GAP: 18.0000
Trial 3 - SMAPE: 61.4900, GAP: 18.0000
Trial 4 - SMAPE: 61.4900, GAP: 18.0000

Número total de Best Trials ('Frente de pareto'): 5

🏆 Best Trial Params:
{'n_estimators': 550, 'max_depth': 1, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': None, 'bootstrap': False}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU21

100%|██████████| 125/125 [01:41<00:00,  1.23it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 39.7200, GAP: 3.6900
Trial 1 - SMAPE: 39.2100, GAP: 3.9600
Trial 2 - SMAPE: 39.2100, GAP: 3.9600
Trial 3 - SMAPE: 37.9600, GAP: 8.6000
Trial 4 - SMAPE: 37.8700, GAP: 8.8500

Número total de Best Trials ('Frente de pareto'): 7

🏆 Best Trial Params:
{'n_estimators': 250, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 9, 'max_features': 'sqrt', 'bootstrap': True}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU22

100%|██████████| 125/125 [02:58<00:00,  1.43s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 35.1300, GAP: 9.7900
Trial 1 - SMAPE: 35.2100, GAP: 9.6500
Trial 2 - SMAPE: 37.0900, GAP: 7.2200
Trial 3 - SMAPE: 35.6400, GAP: 9.1800
Trial 4 - SMAPE: 36.8800, GAP: 8.8400

Número total de Best Trials ('Frente de pareto'): 15

🏆 Best Trial Params:
{'n_estimators': 700, 'max_depth': 8, 'min_samples_split': 3, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU23

100%|██████████| 125/125 [04:35<00:00,  2.21s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 24.8300, GAP: 11.4900
Trial 1 - SMAPE: 24.8300, GAP: 11.4900
Trial 2 - SMAPE: 26.3500, GAP: 9.5700
Trial 3 - SMAPE: 28.0100, GAP: 8.1400
Trial 4 - SMAPE: 28.0100, GAP: 8.1400

Número total de Best Trials ('Frente de pareto'): 30

🏆 Best Trial Params:
{'n_estimators': 250, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 15, 'max_features': None, 'bootstrap': False}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU24

100%|██████████| 125/125 [03:11<00:00,  1.53s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 39.4800, GAP: 8.8600
Trial 1 - SMAPE: 32.9700, GAP: 12.2100
Trial 2 - SMAPE: 32.9700, GAP: 12.2100
Trial 3 - SMAPE: 33.2600, GAP: 11.8700
Trial 4 - SMAPE: 33.2600, GAP: 11.8700

Número total de Best Trials ('Frente de pareto'): 9

🏆 Best Trial Params:
{'n_estimators': 750, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 14, 'max_features': None, 'bootstrap': False}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU25

100%|██████████| 125/125 [02:12<00:00,  1.06s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 41.3600, GAP: 2.5400
Trial 1 - SMAPE: 41.3600, GAP: 2.5400

Número total de Best Trials ('Frente de pareto'): 2

🏆 Best Trial Params:
{'n_estimators': 300, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 13, 'max_features': None, 'bootstrap': False}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU26

100%|██████████| 125/125 [04:22<00:00,  2.10s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 35.9900, GAP: 9.8400
Trial 1 - SMAPE: 37.6200, GAP: 8.8300
Trial 2 - SMAPE: 37.0300, GAP: 9.0000
Trial 3 - SMAPE: 37.6800, GAP: 5.0300
Trial 4 - SMAPE: 37.6800, GAP: 5.0300

Número total de Best Trials ('Frente de pareto'): 17

🏆 Best Trial Params:
{'n_estimators': 250, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 6, 'max_features': None, 'bootstrap': True}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU3

100%|██████████| 125/125 [01:08<00:00,  1.83it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 28.4900, GAP: 6.9600
Trial 1 - SMAPE: 25.9800, GAP: 7.4600
Trial 2 - SMAPE: 27.7800, GAP: 7.2800
Trial 3 - SMAPE: 25.9800, GAP: 7.4600
Trial 4 - SMAPE: 30.4400, GAP: 6.3000

Número total de Best Trials ('Frente de pareto'): 8

🏆 Best Trial Params:
{'n_estimators': 50, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_features': 'log2', 'bootstrap': True}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU4

100%|██████████| 125/125 [03:05<00:00,  1.48s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 18.1000, GAP: 8.8600
Trial 1 - SMAPE: 20.3300, GAP: 6.1300
Trial 2 - SMAPE: 20.4500, GAP: 6.1000
Trial 3 - SMAPE: 18.8800, GAP: 7.5000
Trial 4 - SMAPE: 18.5200, GAP: 8.2600

Número total de Best Trials ('Frente de pareto'): 12

🏆 Best Trial Params:
{'n_estimators': 100, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': True}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU5

100%|██████████| 125/125 [03:38<00:00,  1.75s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 19.1000, GAP: 15.6500
Trial 1 - SMAPE: 27.7600, GAP: 6.2500
Trial 2 - SMAPE: 27.7600, GAP: 6.2500
Trial 3 - SMAPE: 18.7500, GAP: 16.2200
Trial 4 - SMAPE: 18.7500, GAP: 16.2200

Número total de Best Trials ('Frente de pareto'): 24

🏆 Best Trial Params:
{'n_estimators': 400, 'max_depth': 3, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': None, 'bootstrap': True}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU6

100%|██████████| 125/125 [04:09<00:00,  1.99s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 34.1100, GAP: 12.2300
Trial 1 - SMAPE: 30.3100, GAP: 16.3500
Trial 2 - SMAPE: 33.1000, GAP: 13.0300
Trial 3 - SMAPE: 31.9900, GAP: 14.3800
Trial 4 - SMAPE: 30.4300, GAP: 15.9700

Número total de Best Trials ('Frente de pareto'): 13

🏆 Best Trial Params:
{'n_estimators': 600, 'max_depth': 2, 'min_samples_split': 10, 'min_samples_leaf': 9, 'max_features': None, 'bootstrap': True}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU7

100%|██████████| 125/125 [03:02<00:00,  1.46s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 46.2300, GAP: 14.7000
Trial 1 - SMAPE: 46.5100, GAP: 13.1400
Trial 2 - SMAPE: 48.1600, GAP: 8.6900
Trial 3 - SMAPE: 45.9600, GAP: 15.5900
Trial 4 - SMAPE: 48.1700, GAP: 8.5800

Número total de Best Trials ('Frente de pareto'): 34

🏆 Best Trial Params:
{'n_estimators': 550, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': True}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU8

100%|██████████| 125/125 [03:09<00:00,  1.51s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 91.6000, GAP: 31.9600
Trial 1 - SMAPE: 89.5600, GAP: 36.6100
Trial 2 - SMAPE: 89.5600, GAP: 36.6100
Trial 3 - SMAPE: 88.9300, GAP: 36.7100
Trial 4 - SMAPE: 90.0000, GAP: 33.3700

Número total de Best Trials ('Frente de pareto'): 19

🏆 Best Trial Params:
{'n_estimators': 1000, 'max_depth': 1, 'min_samples_split': 10, 'min_samples_leaf': 15, 'max_features': 'sqrt', 'bootstrap': False}
-----------------------

-----------------------
🔍 Optimizando para SKU: SKU9

100%|██████████| 125/125 [05:46<00:00,  2.77s/it]

📌 Mejores Trials:
Trial 0 - SMAPE: 56.2300, GAP: 23.7800
Trial 1 - SMAPE: 57.2500, GAP: 12.4900
Trial 2 - SMAPE: 57.2500, GAP: 12.4900
Trial 3 - SMAPE: 57.1300, GAP: 13.1800
Trial 4 - SMAPE: 57.1300, GAP: 13.1800

Número total de Best Trials ('Frente de pareto'): 15

🏆 Best Trial Params:
{'n_estimators': 1000, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': False}
-----------------------

In [27]:
df_results_rf

,sku,study,best_params,best_smape,best_gap,model,n_trials
0,SKU1,<optuna.study.study.Study object at 0x105e7f140>,"{'n_estimators': 600, 'max_depth': 10, 'min_sa...",32.71,9.59,RandomForestRegressor,125
1,SKU10,<optuna.study.study.Study object at 0x12fd5f4a0>,"{'n_estimators': 50, 'max_depth': 7, 'min_samp...",26.70,6.62,RandomForestRegressor,125
2,SKU11,<optuna.study.study.Study object at 0x12fd5f260>,"{'n_estimators': 550, 'max_depth': 6, 'min_sam...",34.58,5.53,RandomForestRegressor,125
3,SKU12,<optuna.study.study.Study object at 0x12fd5f380>,"{'n_estimators': 450, 'max_depth': 3, 'min_sam...",73.69,31.06,RandomForestRegressor,125
4,SKU13,<optuna.study.study.Study object at 0x12fd5f410>,"{'n_estimators': 1000, 'max_depth': 7, 'min_sa...",37.38,10.28,RandomForestRegressor,125
5,SKU14,<optuna.study.study.Study object at 0x12fd5ff50>,"{'n_estimators': 200, 'max_depth': 3, 'min_sam...",64.53,25.77,RandomForestRegressor,125
6,SKU15,<optuna.study.study.Study object at 0x12fd5f6e0>,"{'n_estimators': 600, 'max_depth': 10, 'min_sa...",50.76,14.53,RandomForestRegressor,125
7,SKU16,<optuna.study.study.Study object at 0x12fd5fad0>,"{'n_estimators': 350, 'max_depth': 8, 'min_sam...",21.51,11.82,RandomForestRegressor,125
8,SKU17,<optuna.study.study.Study object at 0x12fd5fbf0>,"{'n_estimators': 100, 'max_depth': 8, 'min_sam...",35.88,7.44,RandomForestRegressor,125
9,SKU18,<optuna.study.study.Study object at 0x12fd5fa40>,"{'n_estimators': 800, 'max_depth': 1, 'min_sam...",46.02,10.11,RandomForestRegressor,125
10,SKU19,<optuna.study.study.Study object at 0x12fd5f5c0>,"{'n_estimators': 900, 'max_depth': 4, 'min_sam...",67.50,23.71,RandomForestRegressor,125
11,SKU2,<optuna.study.study.Study object at 0x12fd5f530>,"{'n_estimators': 100, 'max_depth': 2, 'min_sam...",30.18,2.30,RandomForestRegressor,125
12,SKU20,<optuna.study.study.Study object at 0x12fb3f0b0>,"{'n_estimators': 550, 'max_depth': 1, 'min_sam...",71.24,14.29,RandomForestRegressor,125
13,SKU21,<optuna.study.study.Study object at 0x12fd5fda0>,"{'n_estimators': 250, 'max_depth': 6, 'min_sam...",39.72,3.69,RandomForestRegressor,125
14,SKU22,<optuna.study.study.Study object at 0x12fd5f890>,"{'n_estimators': 700, 'max_depth': 8, 'min_sam...",35.13,9.79,RandomForestRegressor,125
15,SKU23,<optuna.study.study.Study object at 0x12fd5fb60>,"{'n_estimators': 250, 'max_depth': 7, 'min_sam...",24.83,11.49,RandomForestRegressor,125
16,SKU24,<optuna.study.study.Study object at 0x12fd5fc80>,"{'n_estimators': 750, 'max_depth': 3, 'min_sam...",39.48,8.86,RandomForestRegressor,125
17,SKU25,<optuna.study.study.Study object at 0x12fd5f770>,"{'n_estimators': 300, 'max_depth': 3, 'min_sam...",41.36,2.54,RandomForestRegressor,125
18,SKU26,<optuna.study.study.Study object at 0x12fd5fec0>,"{'n_estimators': 250, 'max_depth': 3, 'min_sam...",35.99,9.84,RandomForestRegressor,125
19,SKU3,<optuna.study.study.Study object at 0x12fd5f650>,"{'n_estimators': 50, 'max_depth': 5, 'min_samp...",28.49,6.96,RandomForestRegressor,125
20,SKU4,<optuna.study.study.Study object at 0x12fd5fd10>,"{'n_estimators': 100, 'max_depth': 9, 'min_sam...",18.10,8.86,RandomForestRegressor,125
21,SKU5,<optuna.study.study.Study object at 0x12fd5f9b0>,"{'n_estimators': 400, 'max_depth': 3, 'min_sam...",19.10,15.65,RandomForestRegressor,125
22,SKU6,<optuna.study.study.Study object at 0x12fd5f920>,"{'n_estimators': 600, 'max_depth': 2, 'min_sam...",34.11,12.23,RandomForestRegressor,125
23,SKU7,<optuna.study.study.Study object at 0x139f97140>,"{'n_estimators': 550, 'max_depth': 6, 'min_sam...",46.23,14.70,RandomForestRegressor,125
24,SKU8,<optuna.study.study.Study object at 0x139f94050>,"{'n_estimators': 1000, 'max_depth': 1, 'min_sa...",91.60,31.96,RandomForestRegressor,125
25,SKU9,<optuna.study.study.Study object at 0x139f94440>,"{'n_estimators': 1000, 'max_depth': 7, 'min_sa...",56.23,23.78,RandomForestRegressor,125

In [28]:
## Mostrar graficas de Optuna por estudio especifico

# sku = "SKU1"
# temp = df_results_rf[df_results_rf["sku"] == sku].copy()
# plot_utils.mostrar_graficas_optuna(temp["study"], temp["model"])

## Evaluación modelos Elastic Net

In [29]:
# Creamos un DataFrame para almacenar los resultados de cada SKU
# Este DataFrame contendrá el SKU, los parámetros del modelo y las métricas de evaluación
##########

results = []

for sku in df_mod["sku"].unique():
    print("\n-----------------------")
    print(f"🔍 Optimizando ElasticNet para SKU: {sku}\n")

    # Filtramos por SKU
    df_sku = df_mod[df_mod["sku"] == sku].copy()
    train_size = df_sku.shape[0] - val_iter * val_size

    # Espacio de búsqueda de hiperparámetros para ElasticNet
    param_grid = {
        "model__alpha": lambda trial: trial.suggest_float(
            "model__alpha", 0.0001, 1000.0, log=True
        ),
        "model__l1_ratio": lambda trial: trial.suggest_float(
            "model__l1_ratio", 0.0, 1.0, step=0.01
        ),  # 0 = Ridge, 1 = Lasso
        "model__random_state": lambda trial: 100,  # Fijamos el random_state para reproducibilidad
    }

    # Pipeline: escalado + modelo
    model_pipeline = Pipeline(
        [("scaler", StandardScaler()), ("model", ElasticNet(max_iter=20000))]
    )

    # Optimización con tu función
    study = ml_utils.optimize_model_with_optuna(
        model_class=lambda **params: model_pipeline.set_params(**params),
        param_grid=param_grid,
        X=df_sku[features],
        y=df_sku["pedidos"],
        n_trials=200,
        val_iter=val_iter,
        train_size=train_size,
        val_size=val_size,
        show_progress_bar=True,
    )

    best_trial = study.best_trials[0]
    results.append(
        {
            "sku": sku,
            "study": study,
            "best_params": best_trial.params,
            "best_smape": best_trial.values[0],
            "best_gap": best_trial.values[1],
            "model": "ElasticNet",
            "n_trials": len(study.trials),
        }
    )

    print("-----------------------")

df_results_elastic = pd.DataFrame(results)

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU1

100%|██████████| 200/200 [00:28<00:00,  7.13it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 27.6900, GAP: 23.5400
Trial 1 - SMAPE: 28.0200, GAP: 23.2300
Trial 2 - SMAPE: 28.8100, GAP: 21.7800
Trial 3 - SMAPE: 27.7600, GAP: 23.4800
Trial 4 - SMAPE: 26.5600, GAP: 26.8300

Número total de Best Trials ('Frente de pareto'): 83

🏆 Best Trial Params:
{'model__alpha': 0.041858227295469716, 'model__l1_ratio': 0.96}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU10

100%|██████████| 200/200 [00:25<00:00,  7.83it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 42.3000, GAP: 4.5900
Trial 1 - SMAPE: 43.0100, GAP: 4.2200
Trial 2 - SMAPE: 28.1900, GAP: 5.1000
Trial 3 - SMAPE: 43.1800, GAP: 4.1300
Trial 4 - SMAPE: 42.8500, GAP: 4.3200

Número total de Best Trials ('Frente de pareto'): 25

🏆 Best Trial Params:
{'model__alpha': 148.9838559398634, 'model__l1_ratio': 0.8300000000000001}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU11

100%|██████████| 200/200 [00:25<00:00,  7.83it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 29.8900, GAP: 3.4200
Trial 1 - SMAPE: 26.8800, GAP: 10.7200
Trial 2 - SMAPE: 29.2500, GAP: 4.0800
Trial 3 - SMAPE: 29.4200, GAP: 3.8100
Trial 4 - SMAPE: 29.6500, GAP: 3.6000

Número total de Best Trials ('Frente de pareto'): 20

🏆 Best Trial Params:
{'model__alpha': 0.0002550264850403288, 'model__l1_ratio': 0.87}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU12

100%|██████████| 200/200 [00:23<00:00,  8.65it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 38.7600, GAP: 17.1600
Trial 1 - SMAPE: 50.2500, GAP: 10.1200
Trial 2 - SMAPE: 39.3100, GAP: 16.6400
Trial 3 - SMAPE: 38.8200, GAP: 17.1000
Trial 4 - SMAPE: 38.8400, GAP: 17.0800

Número total de Best Trials ('Frente de pareto'): 40

🏆 Best Trial Params:
{'model__alpha': 0.009349170414488468, 'model__l1_ratio': 0.08}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU13

100%|██████████| 200/200 [00:08<00:00, 23.19it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 52.7700, GAP: 10.6200
Trial 1 - SMAPE: 52.7700, GAP: 10.6200
Trial 2 - SMAPE: 52.7700, GAP: 10.6200
Trial 3 - SMAPE: 52.7700, GAP: 10.6200
Trial 4 - SMAPE: 52.5400, GAP: 10.7600

Número total de Best Trials ('Frente de pareto'): 79

🏆 Best Trial Params:
{'model__alpha': 619.5023740341801, 'model__l1_ratio': 0.47000000000000003}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU14

100%|██████████| 200/200 [00:42<00:00,  4.74it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 55.2200, GAP: 28.7800
Trial 1 - SMAPE: 50.3000, GAP: 30.8800
Trial 2 - SMAPE: 55.8300, GAP: 28.4600
Trial 3 - SMAPE: 56.0400, GAP: 28.3600
Trial 4 - SMAPE: 52.9200, GAP: 30.7000

Número total de Best Trials ('Frente de pareto'): 58

🏆 Best Trial Params:
{'model__alpha': 0.00015533117206750294, 'model__l1_ratio': 0.03}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU15

100%|██████████| 200/200 [00:28<00:00,  7.04it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 47.5300, GAP: 12.2200
Trial 1 - SMAPE: 48.8300, GAP: 10.7400
Trial 2 - SMAPE: 44.9300, GAP: 14.3200
Trial 3 - SMAPE: 49.8100, GAP: 9.8800
Trial 4 - SMAPE: 51.7300, GAP: 6.7500

Número total de Best Trials ('Frente de pareto'): 65

🏆 Best Trial Params:
{'model__alpha': 0.041858227295469716, 'model__l1_ratio': 0.96}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU16

100%|██████████| 200/200 [00:19<00:00, 10.47it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 20.8800, GAP: 14.6600
Trial 1 - SMAPE: 21.5100, GAP: 13.8400
Trial 2 - SMAPE: 20.7800, GAP: 14.8100
Trial 3 - SMAPE: 21.4400, GAP: 13.9200
Trial 4 - SMAPE: 21.3900, GAP: 13.9800

Número total de Best Trials ('Frente de pareto'): 44

🏆 Best Trial Params:
{'model__alpha': 0.10558813779064824, 'model__l1_ratio': 0.29}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU17

100%|██████████| 200/200 [00:26<00:00,  7.56it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 26.5400, GAP: 21.2500
Trial 1 - SMAPE: 25.7300, GAP: 22.1900
Trial 2 - SMAPE: 25.5100, GAP: 22.7000
Trial 3 - SMAPE: 26.6000, GAP: 21.2200
Trial 4 - SMAPE: 25.9300, GAP: 21.9900

Número total de Best Trials ('Frente de pareto'): 77

🏆 Best Trial Params:
{'model__alpha': 0.0012363188277052211, 'model__l1_ratio': 0.15}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU18

100%|██████████| 200/200 [00:13<00:00, 15.21it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 50.6700, GAP: 15.0600
Trial 1 - SMAPE: 50.8300, GAP: 14.8700
Trial 2 - SMAPE: 50.8300, GAP: 14.8700
Trial 3 - SMAPE: 50.8100, GAP: 14.9000
Trial 4 - SMAPE: 50.7300, GAP: 15.0100

Número total de Best Trials ('Frente de pareto'): 53

🏆 Best Trial Params:
{'model__alpha': 64.51445379907872, 'model__l1_ratio': 0.62}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU19

100%|██████████| 200/200 [00:13<00:00, 14.94it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 65.6500, GAP: 27.0800
Trial 1 - SMAPE: 65.7100, GAP: 27.0300
Trial 2 - SMAPE: 68.5700, GAP: 24.3700
Trial 3 - SMAPE: 68.9700, GAP: 24.1900
Trial 4 - SMAPE: 68.9400, GAP: 24.2000

Número total de Best Trials ('Frente de pareto'): 11

🏆 Best Trial Params:
{'model__alpha': 125.32145724611838, 'model__l1_ratio': 1.0}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU2

100%|██████████| 200/200 [00:14<00:00, 14.14it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 29.4400, GAP: 3.1400
Trial 1 - SMAPE: 22.6300, GAP: 5.3600
Trial 2 - SMAPE: 21.5600, GAP: 5.9900
Trial 3 - SMAPE: 26.1200, GAP: 3.9800
Trial 4 - SMAPE: 28.7600, GAP: 3.4900

Número total de Best Trials ('Frente de pareto'): 114

🏆 Best Trial Params:
{'model__alpha': 1.6136341713591302, 'model__l1_ratio': 0.71}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU20

100%|██████████| 200/200 [00:29<00:00,  6.76it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 55.3400, GAP: 14.0600
Trial 1 - SMAPE: 55.3400, GAP: 14.0600

Número total de Best Trials ('Frente de pareto'): 2

🏆 Best Trial Params:
{'model__alpha': 0.0003585298072319365, 'model__l1_ratio': 1.0}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU21

100%|██████████| 200/200 [00:47<00:00,  4.23it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 29.8400, GAP: 4.1500
Trial 1 - SMAPE: 30.8300, GAP: 3.1300
Trial 2 - SMAPE: 30.2500, GAP: 3.7000
Trial 3 - SMAPE: 30.6600, GAP: 3.2800
Trial 4 - SMAPE: 30.3700, GAP: 3.5800

Número total de Best Trials ('Frente de pareto'): 62

🏆 Best Trial Params:
{'model__alpha': 0.0002550264850403288, 'model__l1_ratio': 0.87}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU22

100%|██████████| 200/200 [00:09<00:00, 20.76it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 32.3800, GAP: 16.8400
Trial 1 - SMAPE: 59.7500, GAP: 8.0000
Trial 2 - SMAPE: 62.0300, GAP: 7.4900
Trial 3 - SMAPE: 57.8800, GAP: 8.4300
Trial 4 - SMAPE: 53.3600, GAP: 9.7300

Número total de Best Trials ('Frente de pareto'): 79

🏆 Best Trial Params:
{'model__alpha': 0.000139345022513376, 'model__l1_ratio': 0.97}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU23

100%|██████████| 200/200 [00:11<00:00, 17.28it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 28.9300, GAP: 8.0000
Trial 1 - SMAPE: 27.9000, GAP: 8.1400
Trial 2 - SMAPE: 25.8500, GAP: 8.3200
Trial 3 - SMAPE: 24.8200, GAP: 8.5300
Trial 4 - SMAPE: 24.7200, GAP: 9.0900

Número total de Best Trials ('Frente de pareto'): 10

🏆 Best Trial Params:
{'model__alpha': 1.8449632796470226, 'model__l1_ratio': 1.0}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU24

100%|██████████| 200/200 [00:09<00:00, 21.49it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 35.4300, GAP: 9.6400
Trial 1 - SMAPE: 33.1200, GAP: 10.1200
Trial 2 - SMAPE: 38.0100, GAP: 8.9200
Trial 3 - SMAPE: 34.0000, GAP: 10.0000
Trial 4 - SMAPE: 36.5600, GAP: 9.1800

Número total de Best Trials ('Frente de pareto'): 33

🏆 Best Trial Params:
{'model__alpha': 309.9764189324157, 'model__l1_ratio': 1.0}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU25

100%|██████████| 200/200 [00:10<00:00, 19.36it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 38.4700, GAP: 2.3700
Trial 1 - SMAPE: 38.8800, GAP: 1.4800
Trial 2 - SMAPE: 38.3700, GAP: 2.6100
Trial 3 - SMAPE: 38.3000, GAP: 2.7900
Trial 4 - SMAPE: 37.0400, GAP: 6.4200

Número total de Best Trials ('Frente de pareto'): 60

🏆 Best Trial Params:
{'model__alpha': 1.6136341713591302, 'model__l1_ratio': 0.71}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU26

100%|██████████| 200/200 [00:11<00:00, 17.84it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 27.4600, GAP: 16.6700
Trial 1 - SMAPE: 31.4900, GAP: 14.1600
Trial 2 - SMAPE: 34.2400, GAP: 13.3700
Trial 3 - SMAPE: 45.4800, GAP: 11.3800
Trial 4 - SMAPE: 28.7800, GAP: 16.3500

Número total de Best Trials ('Frente de pareto'): 70

🏆 Best Trial Params:
{'model__alpha': 0.10558813779064824, 'model__l1_ratio': 0.29}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU3

100%|██████████| 200/200 [00:23<00:00,  8.55it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 20.6200, GAP: 10.6800
Trial 1 - SMAPE: 31.3900, GAP: 6.3400
Trial 2 - SMAPE: 30.3500, GAP: 7.4400
Trial 3 - SMAPE: 30.4600, GAP: 7.3200
Trial 4 - SMAPE: 29.7100, GAP: 8.0500

Número total de Best Trials ('Frente de pareto'): 76

🏆 Best Trial Params:
{'model__alpha': 0.000139345022513376, 'model__l1_ratio': 0.97}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU4

100%|██████████| 200/200 [00:19<00:00, 10.12it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 20.1200, GAP: 7.2000
Trial 1 - SMAPE: 20.4700, GAP: 6.9500
Trial 2 - SMAPE: 19.5000, GAP: 8.2800
Trial 3 - SMAPE: 19.5800, GAP: 8.0900
Trial 4 - SMAPE: 20.4900, GAP: 6.9300

Número total de Best Trials ('Frente de pareto'): 37

🏆 Best Trial Params:
{'model__alpha': 0.0053042909346234695, 'model__l1_ratio': 0.42}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU5

100%|██████████| 200/200 [00:27<00:00,  7.35it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 18.6000, GAP: 11.6700
Trial 1 - SMAPE: 18.9700, GAP: 11.4300
Trial 2 - SMAPE: 18.7200, GAP: 11.6000
Trial 3 - SMAPE: 18.5600, GAP: 11.7000
Trial 4 - SMAPE: 18.6900, GAP: 11.6300

Número total de Best Trials ('Frente de pareto'): 31

🏆 Best Trial Params:
{'model__alpha': 0.0012363188277052211, 'model__l1_ratio': 0.15}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU6

100%|██████████| 200/200 [01:03<00:00,  3.17it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 25.8000, GAP: 4.8100
Trial 1 - SMAPE: 25.7000, GAP: 5.6300
Trial 2 - SMAPE: 25.8100, GAP: 4.7300
Trial 3 - SMAPE: 25.8100, GAP: 4.7300
Trial 4 - SMAPE: 25.8100, GAP: 4.7300

Número total de Best Trials ('Frente de pareto'): 26

🏆 Best Trial Params:
{'model__alpha': 0.00011293569666047012, 'model__l1_ratio': 0.98}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU7

100%|██████████| 200/200 [00:13<00:00, 14.62it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 50.6400, GAP: 4.7500
Trial 1 - SMAPE: 50.6600, GAP: 4.6900
Trial 2 - SMAPE: 41.5200, GAP: 6.6600
Trial 3 - SMAPE: 50.6600, GAP: 4.6900
Trial 4 - SMAPE: 41.4500, GAP: 6.7600

Número total de Best Trials ('Frente de pareto'): 26

🏆 Best Trial Params:
{'model__alpha': 744.9271069389815, 'model__l1_ratio': 0.39}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU8

100%|██████████| 200/200 [00:09<00:00, 20.84it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 72.0200, GAP: 12.9800

Número total de Best Trials ('Frente de pareto'): 1

🏆 Best Trial Params:
{'model__alpha': 233.75241321673985, 'model__l1_ratio': 1.0}
-----------------------

-----------------------
🔍 Optimizando ElasticNet para SKU: SKU9

100%|██████████| 200/200 [00:13<00:00, 15.29it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 50.1800, GAP: 8.5800
Trial 1 - SMAPE: 50.0300, GAP: 8.7600
Trial 2 - SMAPE: 50.4600, GAP: 8.2200
Trial 3 - SMAPE: 50.6900, GAP: 7.9100
Trial 4 - SMAPE: 41.2200, GAP: 8.9400

Número total de Best Trials ('Frente de pareto'): 13

🏆 Best Trial Params:
{'model__alpha': 0.06032030579768781, 'model__l1_ratio': 0.03}
-----------------------

In [30]:
df_results_elastic

,sku,study,best_params,best_smape,best_gap,model,n_trials
0,SKU1,<optuna.study.study.Study object at 0x12fd5e8d0>,"{'model__alpha': 0.041858227295469716, 'model_...",27.69,23.54,ElasticNet,200
1,SKU10,<optuna.study.study.Study object at 0x139f962a0>,"{'model__alpha': 148.9838559398634, 'model__l1...",42.30,4.59,ElasticNet,200
2,SKU11,<optuna.study.study.Study object at 0x139f97410>,"{'model__alpha': 0.0002550264850403288, 'model...",29.89,3.42,ElasticNet,200
3,SKU12,<optuna.study.study.Study object at 0x139f96180>,"{'model__alpha': 0.009349170414488468, 'model_...",38.76,17.16,ElasticNet,200
4,SKU13,<optuna.study.study.Study object at 0x139f97770>,"{'model__alpha': 619.5023740341801, 'model__l1...",52.77,10.62,ElasticNet,200
5,SKU14,<optuna.study.study.Study object at 0x139f949e0>,"{'model__alpha': 0.00015533117206750294, 'mode...",55.22,28.78,ElasticNet,200
6,SKU15,<optuna.study.study.Study object at 0x139f97650>,"{'model__alpha': 0.041858227295469716, 'model_...",47.53,12.22,ElasticNet,200
7,SKU16,<optuna.study.study.Study object at 0x139f94710>,"{'model__alpha': 0.10558813779064824, 'model__...",20.88,14.66,ElasticNet,200
8,SKU17,<optuna.study.study.Study object at 0x139f971d0>,"{'model__alpha': 0.0012363188277052211, 'model...",26.54,21.25,ElasticNet,200
9,SKU18,<optuna.study.study.Study object at 0x139f96450>,"{'model__alpha': 64.51445379907872, 'model__l1...",50.67,15.06,ElasticNet,200
10,SKU19,<optuna.study.study.Study object at 0x139f95760>,"{'model__alpha': 125.32145724611838, 'model__l...",65.65,27.08,ElasticNet,200
11,SKU2,<optuna.study.study.Study object at 0x139f95f40>,"{'model__alpha': 1.6136341713591302, 'model__l...",29.44,3.14,ElasticNet,200
12,SKU20,<optuna.study.study.Study object at 0x139f96690>,"{'model__alpha': 0.0003585298072319365, 'model...",55.34,14.06,ElasticNet,200
13,SKU21,<optuna.study.study.Study object at 0x139f94ef0>,"{'model__alpha': 0.0002550264850403288, 'model...",29.84,4.15,ElasticNet,200
14,SKU22,<optuna.study.study.Study object at 0x139f96b10>,"{'model__alpha': 0.000139345022513376, 'model_...",32.38,16.84,ElasticNet,200
15,SKU23,<optuna.study.study.Study object at 0x139f95d00>,"{'model__alpha': 1.8449632796470226, 'model__l...",28.93,8.00,ElasticNet,200
16,SKU24,<optuna.study.study.Study object at 0x139f97800>,"{'model__alpha': 309.9764189324157, 'model__l1...",35.43,9.64,ElasticNet,200
17,SKU25,<optuna.study.study.Study object at 0x139f97a40>,"{'model__alpha': 1.6136341713591302, 'model__l...",38.47,2.37,ElasticNet,200
18,SKU26,<optuna.study.study.Study object at 0x139f94a70>,"{'model__alpha': 0.10558813779064824, 'model__...",27.46,16.67,ElasticNet,200
19,SKU3,<optuna.study.study.Study object at 0x139f963c0>,"{'model__alpha': 0.000139345022513376, 'model_...",20.62,10.68,ElasticNet,200
20,SKU4,<optuna.study.study.Study object at 0x139f956d0>,"{'model__alpha': 0.0053042909346234695, 'model...",20.12,7.20,ElasticNet,200
21,SKU5,<optuna.study.study.Study object at 0x139f94170>,"{'model__alpha': 0.0012363188277052211, 'model...",18.60,11.67,ElasticNet,200
22,SKU6,<optuna.study.study.Study object at 0x139f952e0>,"{'model__alpha': 0.00011293569666047012, 'mode...",25.80,4.81,ElasticNet,200
23,SKU7,<optuna.study.study.Study object at 0x139f96f00>,"{'model__alpha': 744.9271069389815, 'model__l1...",50.64,4.75,ElasticNet,200
24,SKU8,<optuna.study.study.Study object at 0x139f967b0>,"{'model__alpha': 233.75241321673985, 'model__l...",72.02,12.98,ElasticNet,200
25,SKU9,<optuna.study.study.Study object at 0x139f970b0>,"{'model__alpha': 0.06032030579768781, 'model__...",50.18,8.58,ElasticNet,200

In [31]:
## Mostrar graficas de Optuna por estudio especifico

# sku = "SKU1"
# temp = df_results_elastic[df_results_elastic["sku"] == sku].copy()
# plot_utils.mostrar_graficas_optuna(temp["study"], temp["model"])

## Evaluación modelos KNeighbors

In [32]:
# Creamos un DataFrame para almacenar los resultados de cada SKU
# Este DataFrame contendrá el SKU, los parámetros del modelo y las métricas de evaluación
##########

results = []

for sku in df_mod["sku"].unique():
    print("\n-----------------------")
    print(f"🔍 Optimizando KNN para SKU: {sku}\n")

    df_sku = df_mod[df_mod["sku"] == sku].copy()
    train_size = df_sku.shape[0] - val_iter * val_size

    # Pipeline: escalado obligatorio + modelo
    pipeline = Pipeline(
        [("scaler", StandardScaler()), ("model", KNeighborsRegressor())]
    )

    # Espacio de búsqueda
    param_grid = {
        "model__n_neighbors": lambda trial: trial.suggest_int(
            "model__n_neighbors", 2, 30, step=1
        ),
        "model__weights": lambda trial: trial.suggest_categorical(
            "model__weights", ["uniform", "distance"]
        ),
        "model__p": lambda trial: trial.suggest_int(
            "model__p", 1, 2
        ),  # 1 = manhattan, 2 = euclidean
        "model__leaf_size": lambda trial: trial.suggest_int(
            "model__leaf_size", 5, 100, step=1
        ),
        "model__algorithm": lambda trial: trial.suggest_categorical(
            "model__algorithm", ["auto", "ball_tree", "kd_tree"]
        ),
    }

    # Llamada a tu función personalizada
    study = ml_utils.optimize_model_with_optuna(
        model_class=lambda **params: pipeline.set_params(**params),
        param_grid=param_grid,
        X=df_sku[features],
        y=df_sku["pedidos"],
        n_trials=300,
        val_iter=val_iter,
        train_size=train_size,
        val_size=val_size,
        show_progress_bar=True,
    )

    best_trial = study.best_trials[0]
    results.append(
        {
            "sku": sku,
            "study": study,
            "best_params": best_trial.params,
            "best_smape": best_trial.values[0],
            "best_gap": best_trial.values[1],
            "model": "KNeighborsRegressor",
            "n_trials": len(study.trials),
        }
    )

    print("-----------------------")

df_results_knn = pd.DataFrame(results)

-----------------------
🔍 Optimizando KNN para SKU: SKU1

100%|██████████| 300/300 [00:05<00:00, 54.22it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 44.0000, GAP: 5.9000
Trial 1 - SMAPE: 36.0000, GAP: 13.8800
Trial 2 - SMAPE: 36.0000, GAP: 13.8800
Trial 3 - SMAPE: 36.0000, GAP: 13.8800
Trial 4 - SMAPE: 30.7700, GAP: 24.4100

Número total de Best Trials ('Frente de pareto'): 43

🏆 Best Trial Params:
{'model__n_neighbors': 2, 'model__weights': 'uniform', 'model__p': 2, 'model__leaf_size': 79, 'model__algorithm': 'ball_tree'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU10

100%|██████████| 300/300 [00:05<00:00, 54.97it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 33.8300, GAP: 5.3200
Trial 1 - SMAPE: 33.8300, GAP: 5.3200
Trial 2 - SMAPE: 33.8300, GAP: 5.3200
Trial 3 - SMAPE: 33.8300, GAP: 5.3200
Trial 4 - SMAPE: 32.5700, GAP: 5.4200

Número total de Best Trials ('Frente de pareto'): 55

🏆 Best Trial Params:
{'model__n_neighbors': 8, 'model__weights': 'uniform', 'model__p': 2, 'model__leaf_size': 39, 'model__algorithm': 'kd_tree'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU11

100%|██████████| 300/300 [00:05<00:00, 56.89it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 31.3600, GAP: 10.2300
Trial 1 - SMAPE: 36.2200, GAP: 4.2100
Trial 2 - SMAPE: 34.8300, GAP: 6.6700
Trial 3 - SMAPE: 33.6200, GAP: 6.9100
Trial 4 - SMAPE: 35.5100, GAP: 6.5400

Número total de Best Trials ('Frente de pareto'): 71

🏆 Best Trial Params:
{'model__n_neighbors': 12, 'model__weights': 'uniform', 'model__p': 2, 'model__leaf_size': 19, 'model__algorithm': 'kd_tree'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU12

100%|██████████| 300/300 [00:05<00:00, 56.10it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 80.1300, GAP: 25.9000
Trial 1 - SMAPE: 80.1300, GAP: 25.9000
Trial 2 - SMAPE: 80.2500, GAP: 25.8100
Trial 3 - SMAPE: 78.6500, GAP: 26.0400
Trial 4 - SMAPE: 80.1300, GAP: 25.9000

Número total de Best Trials ('Frente de pareto'): 31

🏆 Best Trial Params:
{'model__n_neighbors': 23, 'model__weights': 'uniform', 'model__p': 1, 'model__leaf_size': 59, 'model__algorithm': 'kd_tree'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU13

100%|██████████| 300/300 [00:05<00:00, 56.65it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 49.9300, GAP: 12.6500
Trial 1 - SMAPE: 49.3100, GAP: 14.2100
Trial 2 - SMAPE: 49.4500, GAP: 13.5700
Trial 3 - SMAPE: 49.9300, GAP: 12.6500
Trial 4 - SMAPE: 49.3100, GAP: 14.2100

Número total de Best Trials ('Frente de pareto'): 62

🏆 Best Trial Params:
{'model__n_neighbors': 25, 'model__weights': 'uniform', 'model__p': 1, 'model__leaf_size': 79, 'model__algorithm': 'kd_tree'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU14

100%|██████████| 300/300 [00:05<00:00, 56.53it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 68.5700, GAP: 31.8600
Trial 1 - SMAPE: 70.0000, GAP: 31.3300
Trial 2 - SMAPE: 70.0000, GAP: 31.3300
Trial 3 - SMAPE: 68.1200, GAP: 32.7800
Trial 4 - SMAPE: 71.8300, GAP: 27.5800

Número total de Best Trials ('Frente de pareto'): 60

🏆 Best Trial Params:
{'model__n_neighbors': 16, 'model__weights': 'uniform', 'model__p': 1, 'model__leaf_size': 67, 'model__algorithm': 'auto'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU15

100%|██████████| 300/300 [00:05<00:00, 57.30it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 50.0200, GAP: 23.5500
Trial 1 - SMAPE: 49.3400, GAP: 24.2600
Trial 2 - SMAPE: 50.0200, GAP: 23.5500
Trial 3 - SMAPE: 49.3400, GAP: 24.2600
Trial 4 - SMAPE: 49.3400, GAP: 24.2600

Número total de Best Trials ('Frente de pareto'): 93

🏆 Best Trial Params:
{'model__n_neighbors': 10, 'model__weights': 'uniform', 'model__p': 1, 'model__leaf_size': 63, 'model__algorithm': 'kd_tree'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU16

100%|██████████| 300/300 [00:05<00:00, 58.30it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 23.2000, GAP: 9.0000
Trial 1 - SMAPE: 21.6100, GAP: 11.8300
Trial 2 - SMAPE: 21.6100, GAP: 11.8300
Trial 3 - SMAPE: 22.1900, GAP: 10.2600
Trial 4 - SMAPE: 20.8600, GAP: 13.0900

Número total de Best Trials ('Frente de pareto'): 56

🏆 Best Trial Params:
{'model__n_neighbors': 4, 'model__weights': 'uniform', 'model__p': 1, 'model__leaf_size': 42, 'model__algorithm': 'ball_tree'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU17

100%|██████████| 300/300 [00:05<00:00, 56.39it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 37.9200, GAP: 18.9100
Trial 1 - SMAPE: 42.5700, GAP: 10.4400
Trial 2 - SMAPE: 38.6400, GAP: 17.5900
Trial 3 - SMAPE: 40.5000, GAP: 14.4000
Trial 4 - SMAPE: 41.8100, GAP: 13.4700

Número total de Best Trials ('Frente de pareto'): 92

🏆 Best Trial Params:
{'model__n_neighbors': 12, 'model__weights': 'uniform', 'model__p': 2, 'model__leaf_size': 19, 'model__algorithm': 'kd_tree'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU18

100%|██████████| 300/300 [00:05<00:00, 55.57it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 41.0500, GAP: 12.0400
Trial 1 - SMAPE: 41.0500, GAP: 12.0400
Trial 2 - SMAPE: 41.0500, GAP: 12.0400
Trial 3 - SMAPE: 45.5500, GAP: 10.6300
Trial 4 - SMAPE: 45.5500, GAP: 10.6300

Número total de Best Trials ('Frente de pareto'): 14

🏆 Best Trial Params:
{'model__n_neighbors': 4, 'model__weights': 'uniform', 'model__p': 2, 'model__leaf_size': 25, 'model__algorithm': 'auto'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU19

100%|██████████| 300/300 [00:05<00:00, 54.93it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 75.8800, GAP: 31.0400
Trial 1 - SMAPE: 75.9700, GAP: 26.7400
Trial 2 - SMAPE: 75.9700, GAP: 26.7400
Trial 3 - SMAPE: 75.9500, GAP: 26.7500
Trial 4 - SMAPE: 75.8800, GAP: 31.0400

Número total de Best Trials ('Frente de pareto'): 27

🏆 Best Trial Params:
{'model__n_neighbors': 4, 'model__weights': 'uniform', 'model__p': 1, 'model__leaf_size': 42, 'model__algorithm': 'ball_tree'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU2

100%|██████████| 300/300 [00:05<00:00, 53.28it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 31.7100, GAP: 4.3700
Trial 1 - SMAPE: 31.7100, GAP: 4.3700
Trial 2 - SMAPE: 31.5900, GAP: 4.7600
Trial 3 - SMAPE: 31.5900, GAP: 4.7600
Trial 4 - SMAPE: 31.7100, GAP: 4.3700

Número total de Best Trials ('Frente de pareto'): 26

🏆 Best Trial Params:
{'model__n_neighbors': 15, 'model__weights': 'uniform', 'model__p': 2, 'model__leaf_size': 61, 'model__algorithm': 'ball_tree'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU20

100%|██████████| 300/300 [00:05<00:00, 55.13it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 71.9700, GAP: 22.0400
Trial 1 - SMAPE: 71.9700, GAP: 22.0400
Trial 2 - SMAPE: 71.3800, GAP: 26.6000
Trial 3 - SMAPE: 71.3800, GAP: 26.6000
Trial 4 - SMAPE: 71.9700, GAP: 22.0400

Número total de Best Trials ('Frente de pareto'): 11

🏆 Best Trial Params:
{'model__n_neighbors': 5, 'model__weights': 'uniform', 'model__p': 1, 'model__leaf_size': 53, 'model__algorithm': 'auto'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU21

100%|██████████| 300/300 [00:05<00:00, 56.38it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 32.6500, GAP: 4.4900
Trial 1 - SMAPE: 31.3000, GAP: 7.3200
Trial 2 - SMAPE: 32.2700, GAP: 6.2700
Trial 3 - SMAPE: 30.4400, GAP: 8.2200
Trial 4 - SMAPE: 30.4400, GAP: 8.2200

Número total de Best Trials ('Frente de pareto'): 81

🏆 Best Trial Params:
{'model__n_neighbors': 4, 'model__weights': 'uniform', 'model__p': 1, 'model__leaf_size': 42, 'model__algorithm': 'ball_tree'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU22

100%|██████████| 300/300 [00:05<00:00, 56.22it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 31.9200, GAP: 18.3100
Trial 1 - SMAPE: 34.5500, GAP: 14.1300
Trial 2 - SMAPE: 35.4500, GAP: 14.0300
Trial 3 - SMAPE: 31.9200, GAP: 18.3100
Trial 4 - SMAPE: 35.4500, GAP: 14.0300

Número total de Best Trials ('Frente de pareto'): 126

🏆 Best Trial Params:
{'model__n_neighbors': 5, 'model__weights': 'uniform', 'model__p': 2, 'model__leaf_size': 29, 'model__algorithm': 'auto'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU23

100%|██████████| 300/300 [00:05<00:00, 55.88it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 30.0400, GAP: 12.2400
Trial 1 - SMAPE: 30.0300, GAP: 13.2700
Trial 2 - SMAPE: 32.5200, GAP: 8.7300
Trial 3 - SMAPE: 34.4200, GAP: 5.0700
Trial 4 - SMAPE: 32.4400, GAP: 10.3700

Número total de Best Trials ('Frente de pareto'): 106

🏆 Best Trial Params:
{'model__n_neighbors': 19, 'model__weights': 'uniform', 'model__p': 2, 'model__leaf_size': 84, 'model__algorithm': 'auto'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU24

100%|██████████| 300/300 [00:05<00:00, 54.79it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 49.1900, GAP: 12.0900
Trial 1 - SMAPE: 49.1900, GAP: 12.0900
Trial 2 - SMAPE: 49.1900, GAP: 12.0900
Trial 3 - SMAPE: 44.2100, GAP: 12.2200
Trial 4 - SMAPE: 44.2100, GAP: 12.2200

Número total de Best Trials ('Frente de pareto'): 11

🏆 Best Trial Params:
{'model__n_neighbors': 25, 'model__weights': 'uniform', 'model__p': 1, 'model__leaf_size': 29, 'model__algorithm': 'auto'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU25

100%|██████████| 300/300 [00:05<00:00, 53.42it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 42.9000, GAP: 2.6700
Trial 1 - SMAPE: 43.8000, GAP: 1.9700
Trial 2 - SMAPE: 42.9000, GAP: 2.6700
Trial 3 - SMAPE: 42.9000, GAP: 2.6700
Trial 4 - SMAPE: 42.9000, GAP: 2.6700

Número total de Best Trials ('Frente de pareto'): 27

🏆 Best Trial Params:
{'model__n_neighbors': 19, 'model__weights': 'uniform', 'model__p': 2, 'model__leaf_size': 84, 'model__algorithm': 'auto'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU26

100%|██████████| 300/300 [00:05<00:00, 55.37it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 38.6700, GAP: 12.7200
Trial 1 - SMAPE: 38.6700, GAP: 12.7200
Trial 2 - SMAPE: 37.2700, GAP: 14.0500
Trial 3 - SMAPE: 37.2700, GAP: 14.0500
Trial 4 - SMAPE: 39.8600, GAP: 9.7300

Número total de Best Trials ('Frente de pareto'): 31

🏆 Best Trial Params:
{'model__n_neighbors': 10, 'model__weights': 'uniform', 'model__p': 1, 'model__leaf_size': 63, 'model__algorithm': 'kd_tree'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU3

100%|██████████| 300/300 [00:05<00:00, 53.46it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 30.3500, GAP: 8.3200
Trial 1 - SMAPE: 30.4900, GAP: 8.1300
Trial 2 - SMAPE: 30.3500, GAP: 8.3200
Trial 3 - SMAPE: 30.3500, GAP: 8.3200
Trial 4 - SMAPE: 30.4900, GAP: 8.1300

Número total de Best Trials ('Frente de pareto'): 30

🏆 Best Trial Params:
{'model__n_neighbors': 25, 'model__weights': 'uniform', 'model__p': 1, 'model__leaf_size': 46, 'model__algorithm': 'ball_tree'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU4

100%|██████████| 300/300 [00:05<00:00, 56.30it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 23.0700, GAP: 11.0700
Trial 1 - SMAPE: 23.0700, GAP: 11.0700
Trial 2 - SMAPE: 21.7600, GAP: 12.8400
Trial 3 - SMAPE: 20.5800, GAP: 14.6700
Trial 4 - SMAPE: 23.0000, GAP: 11.3300

Número total de Best Trials ('Frente de pareto'): 97

🏆 Best Trial Params:
{'model__n_neighbors': 10, 'model__weights': 'uniform', 'model__p': 1, 'model__leaf_size': 63, 'model__algorithm': 'kd_tree'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU5

100%|██████████| 300/300 [00:05<00:00, 54.73it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 25.4300, GAP: 12.0000
Trial 1 - SMAPE: 27.8400, GAP: 9.5200
Trial 2 - SMAPE: 27.8400, GAP: 9.5200
Trial 3 - SMAPE: 27.8400, GAP: 9.5200
Trial 4 - SMAPE: 27.8400, GAP: 9.5200

Número total de Best Trials ('Frente de pareto'): 37

🏆 Best Trial Params:
{'model__n_neighbors': 2, 'model__weights': 'uniform', 'model__p': 2, 'model__leaf_size': 79, 'model__algorithm': 'ball_tree'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU6

100%|██████████| 300/300 [00:05<00:00, 50.19it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 39.8400, GAP: 2.4000
Trial 1 - SMAPE: 39.8400, GAP: 2.4000
Trial 2 - SMAPE: 39.8400, GAP: 2.4000
Trial 3 - SMAPE: 37.1900, GAP: 7.8200
Trial 4 - SMAPE: 37.1900, GAP: 7.8200

Número total de Best Trials ('Frente de pareto'): 45

🏆 Best Trial Params:
{'model__n_neighbors': 5, 'model__weights': 'uniform', 'model__p': 2, 'model__leaf_size': 29, 'model__algorithm': 'auto'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU7

100%|██████████| 300/300 [00:05<00:00, 54.77it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 48.0900, GAP: 6.7100
Trial 1 - SMAPE: 48.0900, GAP: 6.7100
Trial 2 - SMAPE: 48.0900, GAP: 6.7100
Trial 3 - SMAPE: 48.0900, GAP: 6.7100
Trial 4 - SMAPE: 48.0900, GAP: 6.7100

Número total de Best Trials ('Frente de pareto'): 13

🏆 Best Trial Params:
{'model__n_neighbors': 29, 'model__weights': 'uniform', 'model__p': 2, 'model__leaf_size': 54, 'model__algorithm': 'auto'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU8

100%|██████████| 300/300 [00:05<00:00, 56.06it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 88.3100, GAP: 33.6900
Trial 1 - SMAPE: 88.3100, GAP: 33.6900
Trial 2 - SMAPE: 88.3100, GAP: 33.6900
Trial 3 - SMAPE: 88.3100, GAP: 33.6900
Trial 4 - SMAPE: 88.3100, GAP: 33.6900

Número total de Best Trials ('Frente de pareto'): 8

🏆 Best Trial Params:
{'model__n_neighbors': 6, 'model__weights': 'uniform', 'model__p': 2, 'model__leaf_size': 29, 'model__algorithm': 'auto'}
-----------------------

-----------------------
🔍 Optimizando KNN para SKU: SKU9

100%|██████████| 300/300 [00:05<00:00, 56.62it/s]

📌 Mejores Trials:
Trial 0 - SMAPE: 68.4200, GAP: 15.2200
Trial 1 - SMAPE: 68.4200, GAP: 15.2200
Trial 2 - SMAPE: 68.4900, GAP: 15.0700
Trial 3 - SMAPE: 68.4900, GAP: 15.0700
Trial 4 - SMAPE: 68.4900, GAP: 15.0700

Número total de Best Trials ('Frente de pareto'): 11

🏆 Best Trial Params:
{'model__n_neighbors': 22, 'model__weights': 'uniform', 'model__p': 2, 'model__leaf_size': 96, 'model__algorithm': 'kd_tree'}
-----------------------

In [33]:
df_results_knn

,sku,study,best_params,best_smape,best_gap,model,n_trials
0,SKU1,<optuna.study.study.Study object at 0x12fd5e450>,"{'model__n_neighbors': 2, 'model__weights': 'u...",44.00,5.90,KNeighborsRegressor,300
1,SKU10,<optuna.study.study.Study object at 0x139f95130>,"{'model__n_neighbors': 8, 'model__weights': 'u...",33.83,5.32,KNeighborsRegressor,300
2,SKU11,<optuna.study.study.Study object at 0x139f97d10>,"{'model__n_neighbors': 12, 'model__weights': '...",31.36,10.23,KNeighborsRegressor,300
3,SKU12,<optuna.study.study.Study object at 0x139f97890>,"{'model__n_neighbors': 23, 'model__weights': '...",80.13,25.90,KNeighborsRegressor,300
4,SKU13,<optuna.study.study.Study object at 0x139f96330>,"{'model__n_neighbors': 25, 'model__weights': '...",49.93,12.65,KNeighborsRegressor,300
5,SKU14,<optuna.study.study.Study object at 0x139f969f0>,"{'model__n_neighbors': 16, 'model__weights': '...",68.57,31.86,KNeighborsRegressor,300
6,SKU15,<optuna.study.study.Study object at 0x139f97c80>,"{'model__n_neighbors': 10, 'model__weights': '...",50.02,23.55,KNeighborsRegressor,300
7,SKU16,<optuna.study.study.Study object at 0x139f945f0>,"{'model__n_neighbors': 4, 'model__weights': 'u...",23.20,9.00,KNeighborsRegressor,300
8,SKU17,<optuna.study.study.Study object at 0x139f95be0>,"{'model__n_neighbors': 12, 'model__weights': '...",37.92,18.91,KNeighborsRegressor,300
9,SKU18,<optuna.study.study.Study object at 0x13b7c00e0>,"{'model__n_neighbors': 4, 'model__weights': 'u...",41.05,12.04,KNeighborsRegressor,300
10,SKU19,<optuna.study.study.Study object at 0x13b7c29f0>,"{'model__n_neighbors': 4, 'model__weights': 'u...",75.88,31.04,KNeighborsRegressor,300
11,SKU2,<optuna.study.study.Study object at 0x13b7c0440>,"{'model__n_neighbors': 15, 'model__weights': '...",31.71,4.37,KNeighborsRegressor,300
12,SKU20,<optuna.study.study.Study object at 0x13b7c0830>,"{'model__n_neighbors': 5, 'model__weights': 'u...",71.97,22.04,KNeighborsRegressor,300
13,SKU21,<optuna.study.study.Study object at 0x13b7c0680>,"{'model__n_neighbors': 4, 'model__weights': 'u...",32.65,4.49,KNeighborsRegressor,300
14,SKU22,<optuna.study.study.Study object at 0x13b7c1f40>,"{'model__n_neighbors': 5, 'model__weights': 'u...",31.92,18.31,KNeighborsRegressor,300
15,SKU23,<optuna.study.study.Study object at 0x139f97ec0>,"{'model__n_neighbors': 19, 'model__weights': '...",30.04,12.24,KNeighborsRegressor,300
16,SKU24,<optuna.study.study.Study object at 0x139f97e30>,"{'model__n_neighbors': 25, 'model__weights': '...",49.19,12.09,KNeighborsRegressor,300
17,SKU25,<optuna.study.study.Study object at 0x139f951c0>,"{'model__n_neighbors': 19, 'model__weights': '...",42.90,2.67,KNeighborsRegressor,300
18,SKU26,<optuna.study.study.Study object at 0x139f97da0>,"{'model__n_neighbors': 10, 'model__weights': '...",38.67,12.72,KNeighborsRegressor,300
19,SKU3,<optuna.study.study.Study object at 0x139f97f50>,"{'model__n_neighbors': 25, 'model__weights': '...",30.35,8.32,KNeighborsRegressor,300
20,SKU4,<optuna.study.study.Study object at 0x139f95370>,"{'model__n_neighbors': 10, 'model__weights': '...",23.07,11.07,KNeighborsRegressor,300
21,SKU5,<optuna.study.study.Study object at 0x139f97b60>,"{'model__n_neighbors': 2, 'model__weights': 'u...",25.43,12.00,KNeighborsRegressor,300
22,SKU6,<optuna.study.study.Study object at 0x139f943b0>,"{'model__n_neighbors': 5, 'model__weights': 'u...",39.84,2.40,KNeighborsRegressor,300
23,SKU7,<optuna.study.study.Study object at 0x13b7c1760>,"{'model__n_neighbors': 29, 'model__weights': '...",48.09,6.71,KNeighborsRegressor,300
24,SKU8,<optuna.study.study.Study object at 0x13b7c0560>,"{'model__n_neighbors': 6, 'model__weights': 'u...",88.31,33.69,KNeighborsRegressor,300
25,SKU9,<optuna.study.study.Study object at 0x139f95fd0>,"{'model__n_neighbors': 22, 'model__weights': '...",68.42,15.22,KNeighborsRegressor,300

In [34]:
## Mostrar graficas de Optuna por estudio especifico

# sku = "SKU1"
# temp = df_results_knn[df_results_knn["sku"] == sku].copy()
# plot_utils.mostrar_graficas_optuna(temp["study"], temp["model"])

## Selección mejor modelo y ajuste final

In [ ]:
# Eliminamos los estudios de Optuna de todos los DataFrames de resultados
# df_results_xgboost = df_results_xgboost.drop(columns=["study"])
# df_results_rf = df_results_rf.drop(columns=["study"])
# df_results_elastic = df_results_elastic.drop(columns=["study"])
# df_results_knn = df_results_knn.drop(columns=["study"])

# Union de resultados de los modelos
df_results = pd.concat(
    [df_results_xgboost, df_results_rf, df_results_elastic, df_results_knn],
    ignore_index=True,
).sort_values(by=["sku", "best_smape"], ascending=[True, True])

# Por cada SKU, obtenemos el mejor modelo
df_best_models = df_results.loc[
    df_results.groupby("sku")["best_smape"].idxmin()
].reset_index(drop=True)


# Ordenamos por mejor SMAPE
df_best_models = df_best_models.sort_values(by="best_smape", ascending=True).drop(
    columns=["study"]
)

In [36]:
# guardar en OUTPUT_DIR el dataframe de resultados por SKU
output_file = os.path.join(OUTPUT_DIR, "df_ML_models_results.xlsx")
df_results.to_excel(output_file, index=False)

df_results

,sku,study,best_params,best_smape,best_gap,model,n_trials
0,SKU1,<optuna.study.study.Study object at 0x1380c0ad0>,"{'max_depth': 2, 'learning_rate': 0.021, 'n_es...",27.46,1.83,XGBRegressor,125
52,SKU1,<optuna.study.study.Study object at 0x12fd5e8d0>,"{'model__alpha': 0.041858227295469716, 'model_...",27.69,23.54,ElasticNet,200
26,SKU1,<optuna.study.study.Study object at 0x105e7f140>,"{'n_estimators': 600, 'max_depth': 10, 'min_sa...",32.71,9.59,RandomForestRegressor,125
78,SKU1,<optuna.study.study.Study object at 0x12fd5e450>,"{'model__n_neighbors': 2, 'model__weights': 'u...",44.00,5.90,KNeighborsRegressor,300
1,SKU10,<optuna.study.study.Study object at 0x1380634d0>,"{'max_depth': 5, 'learning_rate': 0.076, 'n_es...",25.84,3.78,XGBRegressor,125
...,...,...,...,...,...,...,...
50,SKU8,<optuna.study.study.Study object at 0x139f94050>,"{'n_estimators': 1000, 'max_depth': 1, 'min_sa...",91.60,31.96,RandomForestRegressor,125
77,SKU9,<optuna.study.study.Study object at 0x139f970b0>,"{'model__alpha': 0.06032030579768781, 'model__...",50.18,8.58,ElasticNet,200
51,SKU9,<optuna.study.study.Study object at 0x139f94440>,"{'n_estimators': 1000, 'max_depth': 7, 'min_sa...",56.23,23.78,RandomForestRegressor,125
25,SKU9,<optuna.study.study.Study object at 0x12fd5ea80>,"{'max_depth': 2, 'learning_rate': 0.065, 'n_es...",59.79,41.27,XGBRegressor,125
103,SKU9,<optuna.study.study.Study object at 0x139f95fd0>,"{'model__n_neighbors': 22, 'model__weights': '...",68.42,15.22,KNeighborsRegressor,300

In [44]:
# guardar en OUTPUT_DIR el dataframe de mejores modelos por SKU
output_file = os.path.join(OUTPUT_DIR, "df_ML_best_models.xlsx")
df_best_models.to_excel(output_file, index=False)

df_best_models

,sku,best_params,best_smape,best_gap,model,n_trials
21,SKU5,"{'max_depth': 3, 'learning_rate': 0.095, 'n_es...",16.14,11.97,XGBRegressor,125
20,SKU4,"{'n_estimators': 100, 'max_depth': 9, 'min_sam...",18.10,8.86,RandomForestRegressor,125
19,SKU3,"{'model__alpha': 0.000139345022513376, 'model_...",20.62,10.68,ElasticNet,200
7,SKU16,"{'model__alpha': 0.10558813779064824, 'model__...",20.88,14.66,ElasticNet,200
11,SKU2,"{'max_depth': 5, 'learning_rate': 0.02, 'n_est...",24.81,12.56,XGBRegressor,125
15,SKU23,"{'n_estimators': 250, 'max_depth': 7, 'min_sam...",24.83,11.49,RandomForestRegressor,125
22,SKU6,"{'model__alpha': 0.00011293569666047012, 'mode...",25.80,4.81,ElasticNet,200
1,SKU10,"{'max_depth': 5, 'learning_rate': 0.076, 'n_es...",25.84,3.78,XGBRegressor,125
8,SKU17,"{'model__alpha': 0.0012363188277052211, 'model...",26.54,21.25,ElasticNet,200
18,SKU26,"{'model__alpha': 0.10558813779064824, 'model__...",27.46,16.67,ElasticNet,200
0,SKU1,"{'max_depth': 2, 'learning_rate': 0.021, 'n_es...",27.46,1.83,XGBRegressor,125
13,SKU21,"{'max_depth': 1, 'learning_rate': 0.017, 'n_es...",27.62,4.12,XGBRegressor,125
2,SKU11,"{'model__alpha': 0.0002550264850403288, 'model...",29.89,3.42,ElasticNet,200
14,SKU22,"{'model__n_neighbors': 5, 'model__weights': 'u...",31.92,18.31,KNeighborsRegressor,300
5,SKU14,"{'max_depth': 1, 'learning_rate': 0.063, 'n_es...",34.84,14.82,XGBRegressor,125
16,SKU24,"{'model__alpha': 309.9764189324157, 'model__l1...",35.43,9.64,ElasticNet,200
4,SKU13,"{'n_estimators': 1000, 'max_depth': 7, 'min_sa...",37.38,10.28,RandomForestRegressor,125
17,SKU25,"{'model__alpha': 1.6136341713591302, 'model__l...",38.47,2.37,ElasticNet,200
3,SKU12,"{'model__alpha': 0.009349170414488468, 'model_...",38.76,17.16,ElasticNet,200
9,SKU18,"{'model__n_neighbors': 4, 'model__weights': 'u...",41.05,12.04,KNeighborsRegressor,300
6,SKU15,"{'max_depth': 3, 'learning_rate': 0.028, 'n_es...",43.36,20.57,XGBRegressor,125
23,SKU7,"{'n_estimators': 550, 'max_depth': 6, 'min_sam...",46.23,14.70,RandomForestRegressor,125
25,SKU9,"{'model__alpha': 0.06032030579768781, 'model__...",50.18,8.58,ElasticNet,200
12,SKU20,"{'model__alpha': 0.0003585298072319365, 'model...",55.34,14.06,ElasticNet,200
10,SKU19,"{'model__alpha': 125.32145724611838, 'model__l...",65.65,27.08,ElasticNet,200
24,SKU8,"{'model__alpha': 233.75241321673985, 'model__l...",72.02,12.98,ElasticNet,200

# Predicción y graficas

In [45]:
# Cargar tabla con mejor modelo por SKU
df_best_models_2 = pd.read_excel(
    os.path.join(OUTPUT_DIR, "df_ML_best_models.xlsx"),
    engine="openpyxl",
)

In [50]:
df_best_models_2.sample(2)

,sku,best_params,best_smape,best_gap,model,n_trials
8,SKU17,"{'model__alpha': 0.0012363188277052211, 'model...",26.54,21.25,ElasticNet,200
2,SKU3,"{'model__alpha': 0.000139345022513376, 'model_...",20.62,10.68,ElasticNet,200

In [38]:
# # Reentrenamos la serie de tiempo de cada SKU con el mejor modelo, usando el conjunto de entrenamiento completo
# for sku in df_best_models["sku"].unique():
#     print(f"\n🔍 Reentrenando modelo para SKU: {sku}\n")

#     # Filtramos el DataFrame para el SKU actual
#     df_sku = df[df["sku"] == sku].copy()

#     # Definimos las variables predictoras
#     X = df_sku[features]
#     y = df_sku["pedidos"]

#     # Obtenemos el mejor modelo y sus parámetros
#     best_model_name = df_best_models.loc[df_best_models["sku"] == sku, "model"].values[
#         0
#     ]
#     best_params = df_best_models.loc[
#         df_best_models["sku"] == sku, "best_params"
#     ].values[0]

#     # Creamos el modelo con los mejores parámetros
#     if best_model_name == "XGBRegressor":
#         model = XGBRegressor(**best_params)
#     elif best_model_name == "RandomForestRegressor":
#         model = RandomForestRegressor(**best_params)
#     elif best_model_name == "ElasticNet":
#         model = Pipeline(
#             [
#                 ("scaler", StandardScaler()),
#                 ("model", ElasticNet(**best_params)),
#             ]
#         )
#     else:
#         raise ValueError(f"Modelo desconocido: {best_model_name}")

#     # Entrenamos el modelo con todo el conjunto de entrenamiento
#     model.fit(X, y)

#     # Guardamos el modelo entrenado en un archivo
#     ml_utils.save_model(model, sku, OUTPUT_DIR)